Repository thoth-station/adviser, pull requests merged in 2018-10, with the labels that each got.

#118 Introduce method for converting model to object
  thoth/adviser/python/package_version.py
Labels: approved, size/S

#122 Move from Pods to Jobs
  openshift/job-adviser-template.yaml
  openshift/job-provenanceChecker-template.yaml
  openshift/pod-provenanceChecker-template.yaml
  openshift/pod-template.yaml
Labels: approved, size/L

#123 Move dependency monkey to a job template
  openshift/job-dependencyMonkey.yaml
  openshift/pod-dependencyMonkey.yaml
Labels: size/L

#125 Template fixes
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/S

#124 Link PackageVersion to Source index used
  tests/data/Pipfile_provenance2
  tests/data/Pipfile_provenance2.lock
  tests/data/Pipfile_test1.lock
  tests/python/test_package_version.py
  tests/python/test_provenance.py
  thoth/adviser/python/package_version.py
  thoth/adviser/python/packages.py
  thoth/adviser/python/pipfile.py
  thoth/adviser/python/project.py
Labels: approved, size/L, size/M, size/XL

#129 Output to JSON in adviser
  thoth/adviser/cli.py
Labels: approved, size/XS

#130 using thoth zuul jobs now
  .coafile
  .zuul.yaml
Labels: approved, size/S

#132 Setup py tests
  Pipfile
  Pipfile.lock
  setup.py
Labels: approved, size/XL

#133 Check for latest packages present on indexes
  tests/data/Pipfile_test1
  tests/data/Pipfile_test1.lock
  tests/data/Pipfile_test2
  tests/data/Pipfile_test2.lock
  tests/python/test_project.py
  thoth/adviser/exceptions.py
  thoth/adviser/python/project.py
  thoth/adviser/python/source.py
Labels: size/L
