Repository thoth-station/adviser, pull requests merged in 2018-09, with the labels that each got.

#67 Automatic update of dependency thoth-storages from 0.5.1 to 0.5.2
  Pipfile.lock
Labels: bot

#68 Automatic update of dependency thoth-common from 0.2.5 to 0.2.6
  Pipfile.lock
Labels: bot

#70 Automatic update of dependency thoth-common from 0.2.6 to 0.2.7
  Pipfile.lock
Labels: bot

#69 Introduce provenance checker template
  openshift/pod-provenanceChecker-template.yaml
Labels: approved, size/M

#61 Initial implementation
  .coafile
  .gitignore
  Pipfile
  openshift/pod-template.yaml
  tests/base.py
  tests/data/Pipfile_test1
  tests/data/Pipfile_test1.lock
  tests/data/selinon-warehouse-api.json
  tests/data/simple.html
  tests/python/__init__.py
  tests/python/test_package_version.py
  tests/python/test_pipfile.py
  tests/python/test_project.py
  tests/python/test_source.py
  tests/test_configuration.py
  tests/test_enums.py
  thoth/adviser/__init__.py
  thoth/adviser/cli.py
  thoth/adviser/configuration.py
  thoth/adviser/enums.py
  thoth/adviser/exceptions.py
  thoth/adviser/python/__init__.py
  thoth/adviser/python/exceptions.py
  thoth/adviser/python/package_version.py
  thoth/adviser/python/packages.py
  thoth/adviser/python/pipfile.py
  thoth/adviser/python/project.py
  thoth/adviser/python/source.py
Labels: needs-rebase, size/XXL

#81 Some CI fixes
  thoth/adviser/python/package_version.py
  thoth/adviser/python/project.py
Labels: size/XS

#82 Fix warehouse test
  tests/test_configuration.py
  thoth/adviser/configuration.py
Labels: approved, size/S

#83 Use local tensorflow index page for gathering versions
  tests/data/tensorflow.html
  tests/python/test_source.py
  thoth/adviser/python/source.py
Labels: approved, size/L

#85 Remove unused script as adviser is s2i now
  build.sh
Labels: approved, size/XS

#86 Provide entrypoint for OpenShift s2i
  app.py
Labels: approved, size/M

#84 Let's reuse parameter names from adviser
  openshift/pod-provenanceChecker-template.yaml
Labels: size/S

#87 State we want to run provenance rather than adviser in template
  openshift/pod-provenanceChecker-template.yaml
Labels: approved, size/XS

#88 Provide a script to run desired subcommand
  app.sh
Labels: approved, size/S

#80 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XXL

#90 Add execute bit to app.sh
  app.sh
Labels: size/XS

#91 Install forgotten packages
  setup.py
Labels: size/XS

#93 Configure JanusGraph
  openshift/pod-provenanceChecker-template.yaml
  openshift/pod-template.yaml
Labels: size/XS

#92 Pass full path to Python3 in s2i
  app.sh
Labels: size/XS

#89 Revert "Provide entrypoint for OpenShift s2i"
  app.py
Labels: size/M

#94 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XXL

#98 Setuptools find_packages does not respect namespaces
  setup.py
Labels: size/XS

#100 Release of version 0.1.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/XS

#102 Introduce add_source and add_package methods
  tests/python/test_project.py
  thoth/adviser/python/packages.py
  thoth/adviser/python/pipfile.py
  thoth/adviser/python/project.py
  thoth/adviser/python/source.py
Labels: size/L, size/M

#105 Release of version 0.2.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/XS

#101 Do not use command in openshift template
  openshift/pod-template.yaml
Labels: approved, size/XS

#107 Ignore s2i's virtualenv in which adviser is run
  thoth/adviser/python/project.py
Labels: approved, size/XS

#108 Report back error if we cannot conclude on application stack
  thoth/adviser/python/exceptions.py
  thoth/adviser/python/project.py
Labels: approved, size/M

#109 Adviser report should be always an array
  thoth/adviser/cli.py
Labels: approved, size/S

#110 Report directly findings in the provenance check report
  thoth/adviser/python/project.py
Labels: size/XS

#111 Finish provenance reports
  tests/data/Pipfile_provenance1
  tests/data/Pipfile_provenance1.lock
  tests/data/Pipfile_provenance2
  tests/data/Pipfile_provenance2.lock
  tests/python/test_provenance.py
  thoth/adviser/configuration.py
  thoth/adviser/python/project.py
  thoth/adviser/python/source.py
Labels: approved, size/L

#113 Document provenance checks
  README.rst
  tests/python/test_provenance.py
  thoth/adviser/python/project.py
Labels: approved, size/L
