Repository thoth-station/adviser, pull requests merged in 2018-07, with the labels that each got.

#20 Automatic update of dependency thoth-storages from 0.0.32 to 0.0.33
  Pipfile.lock
Labels: approved, bot, size/S

#17 Automatic update of dependency thoth-analyzer from 0.0.5 to 0.0.6
  Pipfile.lock
Labels: approved, bot, size/S

#21 Automatic update of dependency thoth-analyzer from 0.0.6 to 0.0.7
  Pipfile.lock
Labels: bot

#23 Automatic update of dependency thoth-common from 0.0.9 to 0.1.0
  Pipfile.lock
Labels: approved, bot

#30 Initial dependency lock
  Pipfile.lock
Labels: bot

#32 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#33 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#36 Automatic update of dependency thoth-storages from 0.0.33 to 0.1.0
  Pipfile.lock
Labels: bot

#38 Fix coala naming convention configuration
  .coafile
Labels: approved

#37 Add OpenShift templates for deployment
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/pod-template.yaml
Labels: approved

#39 Fix image stream kind in template
  openshift/imageStream-template.yaml
Labels: approved

#43 Automatic update of dependency thoth-storages from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: bot

#44 Automatic update of dependency thoth-common from 0.2.1 to 0.2.2
  Pipfile.lock
Labels: bot

#45 Update requirements.txt respecting requirements in Pipfile
  requirements.txt
Labels: bot, size/XS

#46 Be consistent with label naming
  openshift/pod-template.yaml
Labels: approved, size/XS
