Repository thoth-station/adviser, pull requests merged in 2019-10, with the labels that each got.

#429 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#430 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#431 Automatic update of dependency pytest-cov from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#432 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#433 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#435 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#437 Add spaces to fix toml issues
  tests/python/pipeline/sieves/test_prereleases.py
Labels: approved, size/XS

#438 Automatic update of dependency thoth-python from 0.6.3 to 0.6.4
  Pipfile.lock
Labels: bot

#441 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#443 Automatic update of dependency pylint from 2.4.2 to 2.4.3
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#442 Automatic update of dependency thoth-python from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#445 Pin thoth libraries which will have incompatible release
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#446 Automatic update of dependency methodtools from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: bot

#447 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#448 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#449 Do not use cached adviser
  openshift/buildConfig-cached-template.yaml
  openshift/imageStream-cached-template.yaml
  openshift/job-adviser-template.yaml
Labels: approved, size/L

#450 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#451 Automatic update of dependency methodtools from 0.1.1 to 0.1.2
  Pipfile.lock
Labels: bot

#452 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/S

#453 Use THOTH_ADVISE variable for consistency
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#455 Release of version 0.6.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/L
