Repository thoth-station/adviser, pull requests merged in 2019-05, with the labels that each got.

#246 Automatic update of dependency mock from 2.0.0 to 3.0.2
  Pipfile.lock
Labels: bot

#247 Automatic update of dependency mock from 3.0.2 to 3.0.3
  Pipfile.lock
Labels: bot

#249 Automatic update of dependency pytest-cov from 2.6.1 to 2.7.1
  Pipfile.lock
Labels: bot

#252 Automatic update of dependency thoth-storages from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: bot

#251 Log message was missleading if package_tuple is overwritten
  thoth/adviser/python/pipeline/step_context.py
Labels: size/XS

#250 Provide fast-path when checking for already removed packages
  thoth/adviser/python/pipeline/step_context.py
Labels: size/XS

#248 Implement build-time error filtering step
  tests/python/pipeline/steps/test_buildtime_error.py
  thoth/adviser/cli.py
  thoth/adviser/python/pipeline/steps/buildtime_error.py
Labels: size/M

#254 Automatic update of dependency mock from 3.0.3 to 3.0.4
  Pipfile.lock
Labels: bot

#255 Add information about library usage to pipeline and OpenShift job
  openshift/job-adviser-template.yaml
  thoth/adviser/cli.py
  thoth/adviser/python/advise.py
  thoth/adviser/python/pipeline/pipeline.py
  thoth/adviser/python/pipeline/unit_base.py
Labels: approved, size/M

#253 Fixes to make adviser work with runtime scenario
  tests/python/pipeline/steps/test_buildtime_error.py
  thoth/adviser/python/pipeline/step_context.py
  thoth/adviser/python/pipeline/steps/buildtime_error.py
  thoth/adviser/python/pipeline/steps/toolchain.py
  thoth/adviser/python/pipeline_configuration.py
Labels: size/M, size/S, size/XS

#257 Automatic update of dependency mock from 3.0.4 to 3.0.5
  Pipfile.lock
Labels: bot

#258 Use new method to obtain even large stacks from graph database
  thoth/adviser/python/pipeline/pipeline.py
  thoth/adviser/python/solver.py
Labels: size/M

#261 Automatic update of dependency thoth-storages from 0.11.1 to 0.11.2
  Pipfile.lock
Labels: bot

#262 Automatic update of dependency pytest from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot

#263 Fix coala issues
  thoth/adviser/python/pipeline/pipeline.py
Labels: size/M

#266 Automatic update of dependency thoth-storages from 0.11.2 to 0.11.3
  Pipfile.lock
Labels: bot

#267 Create pipeline builder abstraction
  tests/python/pipeline/steps/test_buildtime_error.py
  tests/python/pipeline/steps/test_cve.py
  tests/python/pipeline/steps/test_limit_latest_versions.py
  tests/python/pipeline/steps/test_performance_adjustment.py
  tests/python/pipeline/steps/test_prereleases.py
  tests/python/pipeline/steps/test_restrict_indexes.py
  tests/python/pipeline/steps/test_semver_sort.py
  tests/python/pipeline/steps/test_toolchain.py
  tests/python/pipeline/steps/test_unreachable.py
  tests/python/pipeline/strides/test_cve.py
  tests/python/pipeline/strides/test_performance_scoring.py
  tests/python/pipeline/strides/test_random_decision.py
  tests/python/pipeline/strides/test_score_filter.py
  tests/python/pipeline/test_pipeline.py
  thoth/adviser/cli.py
  thoth/adviser/python/advise.py
  thoth/adviser/python/builder.py
  thoth/adviser/python/dependency_monkey.py
  thoth/adviser/python/pipeline/pipeline.py
  thoth/adviser/python/pipeline/step_context.py
Labels: size/L, size/XL

#269 Log number of packages considered during dependency graph traversals
  thoth/adviser/python/pipeline/pipeline.py
Labels: size/S

#268 Re-introduce filedump for fixes on long-lasting queries
  thoth/adviser/python/pipeline/pipeline.py
Labels: size/S

#270 Automatic update of dependency thoth-storages from 0.11.3 to 0.11.4
  Pipfile.lock
Labels: bot

#271 Automatic update of dependency pytest from 4.4.2 to 4.5.0
  Pipfile.lock
Labels: bot

#265 Release of version 0.4.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/L

#272 Place toolchain cut after semver sort
  thoth/adviser/python/builder.py
Labels: approved, size/XS

#276 Use defaults of -1 for "unlimited" numbers in the cluster
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
Labels: approved

#275 Parse a special value of -1 in the cluster to workaround click's errors
  thoth/adviser/cli.py
Labels: approved

#274 Be more user-friendly in cluster logs
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved

#280 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#284 Update documentation to respect current state
  docs/source/_static/dependency_graph.png
  docs/source/dependency_graph.rst
  docs/source/dependency_monkey.rst
  docs/source/libdependency_graph.rst
  docs/source/pipeline.rst
Labels: approved

#282 Use uint16_t for representing packages in libdependency graph
  tests/python/bin/test_dependency_graph.py
  thoth/adviser/python/bin/__init__.py
  thoth/adviser/python/bin/dependency_graph.h
  thoth/adviser/python/bin/dependency_graph.py
  thoth/adviser/python/bin/libdependency_graph.so
  thoth/adviser/python/bin/stack_item.h
Labels: approved, needs-rebase

#277 Provide better report to user on why adviser has stopped prematurely
  liveness.py
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved

#278 Give adviser more time to process rest of the stacks in queue
  openshift/job-adviser-template.yaml
Labels: approved

#285 Keep stats for package removals per step run
  thoth/adviser/python/pipeline/step_context.py
  thoth/adviser/python/pipeline/step_stats.py
Labels: approved

#287 Optimize package removal by working on indexes instead of package tuples
  thoth/adviser/python/pipeline/step_context.py
Labels: approved
