Repository thoth-station/adviser, pull requests merged in 2019-08, with the labels that each got.

#338 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#340 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#341 Add docs for performance indicators
  docs/source/index.rst
  docs/source/performance.rst
Labels: approved, size/L

#342 Update docs and introduce sieve abstraction
  docs/source/_static/pipeline.dia
  docs/source/_static/pipeline.png
  docs/source/index.rst
  docs/source/pipeline.rst
Labels: approved, size/L, size/XL

#344 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#345 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#347 Fix reference to variable - do not pass class
  docs/source/pipeline.rst
Labels: approved, size/XS

#351 Do not treat builds as pre-releases
  thoth/adviser/python/pipeline/steps/prereleases.py
Labels: size/XS

#346 Fix resolving direct dependencies based on the score
  thoth/adviser/python/pipeline/pipeline.py
Labels: size/XS

#352 Do not remove package tuples which are direct dependencies
  thoth/adviser/python/dependency_graph/adaptation/graph.py
Labels: size/XS

#355 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thoth_template.yaml
  openshift/buildConfig-template.yaml
Labels: size/M, size/S

#356 Change name of Thoth template to make Coala happy
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/XS

#357 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#359 Automatic update of dependency thoth-python from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot

#360 Automatic update of dependency voluptuous from 0.11.5 to 0.11.7
  Pipfile.lock
Labels: bot

#358 A package can be removed in the previous sub-graphs removals
  docs/source/pipeline.rst
  thoth/adviser/python/pipeline/steps/observation_reduction.py
Labels: size/S, size/XS

#362 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#363 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#364 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#366 Automatic update of dependency pydocstyle from 4.0.0 to 4.0.1
  Pipfile.lock
Labels: bot

#367 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#369 Fix missing packages in adviser's package
  setup.py
Labels: approved, size/XS

#368 State how to integrate with Thoth in docs
  docs/source/index.rst
  docs/source/integration.rst
Labels: approved, size/M

#374 Improve error message reported if no releases were found
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved, size/M, size/S

#375 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#372 Do not use setuptools.find_namespace_packages() for now
  setup.py
Labels: approved, size/S

#371 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: size/M

#376 Turn error into warning
  thoth/adviser/python/pipeline/pipeline.py
Labels: size/XS

#378 Automatic update of dependency semantic-version from 2.6.0 to 2.7.0
  Pipfile.lock
Labels: bot

#379 Automatic update of dependency semantic-version from 2.7.0 to 2.7.1
  Pipfile.lock
Labels: bot

#381 Automatic update of dependency semantic-version from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#382 Automatic update of dependency semantic-version from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#383 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
