Repository thoth-station/adviser, pull requests merged in 2019-11, with the labels that each got.

#461 Automatic update of dependency hypothesis from 4.42.0 to 4.42.4
  Pipfile.lock
Labels: bot

#462 Release of version 0.6.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/L

#463 Automatic update of dependency hypothesis from 4.42.4 to 4.42.5
  Pipfile.lock
Labels: bot

#464 Automatic update of dependency hypothesis from 4.42.5 to 4.42.6
  Pipfile.lock
Labels: bot

#465 Automatic update of dependency hypothesis from 4.42.6 to 4.42.7
  Pipfile.lock
Labels: bot

#466 Automatic update of dependency hypothesis from 4.42.7 to 4.42.8
  Pipfile.lock
Labels: bot

#467 Automatic update of dependency hypothesis from 4.42.8 to 4.42.9
  Pipfile.lock
Labels: bot

#468 Automatic update of dependency hypothesis from 4.42.9 to 4.42.10
  Pipfile.lock
Labels: bot

#469 Automatic update of dependency pytest-mypy from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#470 Automatic update of dependency hypothesis from 4.42.10 to 4.43.0
  Pipfile.lock
Labels: bot

#471 Automatic update of dependency hypothesis from 4.43.0 to 4.43.1
  Pipfile.lock
Labels: bot

#472 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#476 Automatic update of dependency hypothesis from 4.43.1 to 4.43.2
  Pipfile.lock
Labels: bot

#474 Cache queries for retrieving enabled indexes
  thoth/adviser/sieves/index_enabled.py
Labels: approved, size/M, size/S, size/XS

#473 Fix resolving direct dependencies when pagination is used
  tests/graph_mock.py
  thoth/adviser/solver.py
Labels: approved, size/M, size/S

#477 Automatic update of dependency hypothesis from 4.43.2 to 4.43.3
  Pipfile.lock
Labels: bot

#478 Automatic update of dependency hypothesis from 4.43.3 to 4.43.4
  Pipfile.lock
Labels: bot

#475 Use slots on pipeline unit instances
  thoth/adviser/sieves/prereleases.py
  thoth/adviser/sieves/solved.py
  thoth/adviser/steps/cve.py
  thoth/adviser/strides/random_decision.py
  thoth/adviser/strides/score_filter.py
Labels: approved, size/S

#479 Automatic update of dependency hypothesis from 4.43.4 to 4.43.5
  Pipfile.lock
Labels: bot

#481 Release of version 0.6.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/S

#483 runtime_environment var should be dict in parameter
  thoth/adviser/cli.py
Labels: approved, size/XS

#486 Revert "runtime_environment var should be dict in parameter"
  thoth/adviser/cli.py
Labels: approved, size/XS

#488 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#487 Adjust provenance-checker output to be in alaign with adviser and dm
  thoth/adviser/cli.py
Labels: approved, size/XS

#489 Automatic update of dependency hypothesis from 4.43.5 to 4.43.6
  Pipfile.lock
Labels: bot

#484 Fix exit code propagation to the main process
  thoth/adviser/cli.py
  thoth/adviser/run.py
Labels: approved, size/XS

#491 Update README to show how to run adviser locally
  README.rst
Labels: approved, size/S

#493 Automatic update of dependency hypothesis from 4.43.6 to 4.43.8
  Pipfile.lock
Labels: bot

#490 Use new solver implementation
  Pipfile.lock
  tests/test_solver.py
  thoth/adviser/anneal.py
  thoth/adviser/sieves/index_enabled.py
  thoth/adviser/sieves/prereleases.py
  thoth/adviser/solver.py
Labels: approved, size/L

#495 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#499 Automatic update of dependency hypothesis from 4.43.8 to 4.44.0
  Pipfile.lock
Labels: bot

#500 Automatic update of dependency hypothesis from 4.44.0 to 4.44.1
  Pipfile.lock
Labels: bot

#501 Automatic update of dependency hypothesis from 4.44.1 to 4.44.2
  Pipfile.lock
Labels: bot

#502 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#504 Notify when a new pipeline product was produced
  thoth/adviser/resolver.py
Labels: approved, size/XS

#503 Notify user when computing recommendations
  thoth/adviser/resolver.py
Labels: approved, size/XS

#510 Fix hashes representation in the generated Pipfile.lock
  Pipfile.lock
  tests/test_product.py
Labels: approved, size/M

#506 Remove Dgraph leftovers
  README.rst
Labels: approved, do-not-merge/needs-rebase, size/XS

#507 Remove score filter stride
  tests/strides/test_score_filter.py
  thoth/adviser/strides/__init__.py
  thoth/adviser/strides/score_filter.py
Labels: approved, size/L

#511 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.21
  Pipfile.lock
Labels: bot, size/XS

#512 Automatic update of dependency thoth-storages from 0.19.21 to 0.19.22
  Pipfile.lock
Labels: bot, size/XS

#514 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#515 Automatic update of dependency hypothesis from 4.44.2 to 4.44.4
  Pipfile.lock
Labels: bot, size/S

#516 Automatic update of dependency hypothesis from 4.44.4 to 4.45.0
  Pipfile.lock
Labels: bot, size/M

#517 Automatic update of dependency hypothesis from 4.45.0 to 4.45.1
  Pipfile.lock
Labels: bot, size/XS

#518 Remove unused imports
  thoth/adviser/cli.py
Labels: approved, size/XS

#521 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#522 Automatic update of dependency matplotlib from 3.1.1 to 3.1.2
  Pipfile.lock
Labels: bot, size/M

#523 Automatic update of dependency hypothesis from 4.45.1 to 4.46.0
  Pipfile.lock
Labels: bot, size/XS

#524 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#525 Automatic update of dependency hypothesis from 4.46.0 to 4.46.1
  Pipfile.lock
Labels: bot, size/S

#526 Automatic update of dependency hypothesis from 4.46.1 to 4.47.0
  Pipfile.lock
Labels: bot, size/XS

#527 Automatic update of dependency hypothesis from 4.47.0 to 4.47.1
  Pipfile.lock
Labels: bot, size/XS

#528 Automatic update of dependency hypothesis from 4.47.1 to 4.47.2
  Pipfile.lock
Labels: bot, size/S

#529 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#530 Automatic update of dependency hypothesis from 4.47.2 to 4.47.3
  Pipfile.lock
Labels: bot, size/S

#533 Automatic update of dependency hypothesis from 4.47.3 to 4.47.4
  Pipfile.lock
Labels: bot

#536 Automatic update of dependency hypothesis from 4.47.4 to 4.48.0
  Pipfile.lock
Labels: bot, size/S

#537 Automatic update of dependency hypothesis from 4.48.0 to 4.49.0
  Pipfile.lock
Labels: bot, size/XS

#538 Automatic update of dependency hypothesis from 4.49.0 to 4.50.0
  Pipfile.lock
Labels: bot, size/XS

#539 Automatic update of dependency hypothesis from 4.50.0 to 4.50.1
  Pipfile.lock
Labels: bot, size/XS

#540 Automatic update of dependency hypothesis from 4.50.1 to 4.50.2
  Pipfile.lock
Labels: bot, size/L

#534 Propagate document id into jobs
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/S

#532 More tests
  tests/base.py
  tests/conftest.py
  tests/data/projects/Pipfile
  tests/data/projects/Pipfile.lock
  tests/test_beam.py
  tests/test_context.py
  tests/test_pipeline_builder.py
  tests/test_resolver.py
  tests/test_unit.py
  thoth/adviser/beam.py
  thoth/adviser/context.py
  thoth/adviser/pipeline_config.py
  thoth/adviser/report.py
  thoth/adviser/resolver.py
  thoth/adviser/sieve.py
  thoth/adviser/state.py
Labels: approved, size/XXL

#543 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/M

#544 Sieve now accepts and returns a generator of package versions
  tests/sieves/test_index_enabled.py
  tests/sieves/test_prereleases.py
  tests/sieves/test_solved.py
  tests/test_resolver.py
  tests/units/sieves.py
  thoth/adviser/beam.py
  thoth/adviser/cli.py
  thoth/adviser/resolver.py
  thoth/adviser/run.py
  thoth/adviser/sieve.py
  thoth/adviser/sieves/index_enabled.py
  thoth/adviser/sieves/prereleases.py
  thoth/adviser/sieves/solved.py
Labels: approved, size/XL
