Repository thoth-station/adviser, pull requests merged in 2019-06, with the labels that each got.

#292 Automatic update of dependency pytest from 4.5.0 to 4.6.2
  Pipfile.lock
Labels: bot

#294 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#296 Updated Readme to Dgraph examples
  README.rst
Labels: approved, size/S

#297 Automatic update of dependency pytest from 4.6.2 to 4.6.3
  Pipfile.lock
Labels: bot

#299 Add build trigger with generic webhook
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#300 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#302 Increase default adviser's requests and limits
  openshift/job-adviser-template.yaml
Labels: approved, size/XS
