Repository thoth-station/adviser, pull requests merged in 2019-09, with the labels that each got.

#385 Automatic update of dependency semantic-version from 2.8.1 to 2.8.2
  Pipfile.lock
Labels: bot

#388 Drop generic performance querying
  tests/python/pipeline/steps/test_performance_adjustment.py
  tests/python/pipeline/strides/test_performance_scoring.py
  thoth/adviser/python/builder.py
  thoth/adviser/python/pipeline/steps/__init__.py
  thoth/adviser/python/pipeline/steps/performance_adjustment.py
  thoth/adviser/python/pipeline/strides/__init__.py
  thoth/adviser/python/pipeline/strides/performance_scoring.py
  thoth/adviser/python/pipeline/units/__init__.py
  thoth/adviser/python/pipeline/units/performance.py
Labels: approved, size/L, size/XL

#391 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#392 Automatic update of dependency thoth-python from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot

#390 Propagate runtime environment explicitly
  thoth/adviser/cli.py
Labels: approved, size/XS

#387 Start using PostgreSQL in deployment
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/L

#393 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#395 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#394 Propagate deployment name for sentry environment
  openshift/buildConfig-cached-template.yaml
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/S

#396 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#397 Add Sentry DSN to build of adviser-cached
  openshift/buildConfig-cached-template.yaml
Labels: approved, size/XS

#398 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#399 Corrected typos
  README.rst
Labels: approved, size/S

#400 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#401 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#402 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#405 Automatic update of dependency thoth-analyzer from 0.1.2 to 0.1.3
  Pipfile.lock
Labels: bot

#406 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#407 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#409 Automatic update of dependency thoth-python from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: bot

#408 Introduce tests for checking correct parsing of AICoE releases
  tests/python/pipeline/sieves/test_os_sieve.py
  tests/python/pipeline/test_unit_base.py
  thoth/adviser/python/pipeline/unit_base.py
Labels: approved, size/L

#411 Automatic update of dependency pylint from 2.3.1 to 2.4.0
  Pipfile.lock
Labels: bot

#410 use postgresql hostname from thoth configmap
  openshift/buildConfig-cached-template.yaml
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/S

#412 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#414 Automatic update of dependency pylint from 2.4.0 to 2.4.1
  Pipfile.lock
Labels: bot

#418 Just a minor change to make code great again
  thoth/adviser/python/pipeline/steps/limit_latest_versions.py
Labels: approved, size/XS

#415 Introduce sieve for limiting number of latest versions in direct dependencies
  tests/python/pipeline/sieves/test_limit_latest_versions.py
  tests/python/pipeline/test_sieve_context.py
  thoth/adviser/python/pipeline/sieve_context.py
  thoth/adviser/python/pipeline/sieves/__init__.py
  thoth/adviser/python/pipeline/sieves/limit_latest_versions.py
Labels: approved, size/L

#417 Add a new sieve for limiting pre-releases in direct dependencies
  tests/python/pipeline/sieves/test_prereleases.py
  thoth/adviser/python/pipeline/sieves/__init__.py
  thoth/adviser/python/pipeline/sieves/prereleases.py
Labels: approved, size/L

#404 Add seldon and seldon-core to cached packages
  cache_config.yaml
Labels: approved, size/XS

#419 Check we do not raise exception if os sieve wants to filter out all packages
  tests/python/pipeline/sieves/test_os_sieve.py
Labels: approved, size/M

#403 Create a check and test case to handle errors when trying to resolve unsolved packages
  tests/python/pipeline/test_pipeline.py
  thoth/adviser/python/pipeline/exceptions.py
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved, size/M

#420 Re-anable operating system sieve
  thoth/adviser/python/builder.py
Labels: approved, size/S

#421 Add duration to Adviser
  thoth/adviser/cli.py
Labels: approved, size/S

#423 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#424 Automatic update of dependency thoth-analyzer from 0.1.3 to 0.1.4
  Pipfile.lock
Labels: bot

#422 Fix duration calculation
  thoth/adviser/cli.py
Labels: approved, size/XS

#425 Fix duration
  thoth/adviser/cli.py
Labels: approved, size/XS

#426 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot

#427 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot

#428 Automatic update of dependency pylint from 2.4.1 to 2.4.2
  Pipfile.lock
Labels: bot
