Repository thoth-station/adviser, pull requests merged in 2019-03, with the labels that each got.

#209 Fix testsuite
  .thoth.yaml
  Pipfile.lock
  tests/python/test_dependency_graph.py
Labels: size/L

#211 Make reports more human readable
  thoth/adviser/python/bin/dependency_graph.py
  thoth/adviser/python/dependency_graph.py
  thoth/adviser/python/helpers.py
  thoth/adviser/python/scoring.py
Labels: size/M

#212 Automatic update of dependency thoth-python from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#213 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#214 Improve handling of long-running advises
  liveness.py
  openshift/job-adviser-template.yaml
  thoth/adviser/python/advise.py
  thoth/adviser/python/dependency_graph.py
  thoth/adviser/python/scoring.py
Labels: size/S

#216 Automatic update of dependency flexmock from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot

#218 ImageStream Tag and Namespace
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/L

#221 sane default for IMAGE_STREAM_NAMESPACE
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: size/M

#222 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
