Repository thoth-station/adviser, pull requests merged in 2019-04, with the labels that each got.

#223 Automatic update of dependency thoth-common from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#224 Make Isis a proper adapter
  thoth/adviser/isis.py
Labels: size/M

#225 Automatic update of dependency thoth-common from 0.8.2 to 0.8.3
  Pipfile.lock
Labels: bot

#227 added the Registry to be used for image pulling to the templates
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/M

#228 Create a workaround for click argument parsing from env vars
  openshift/job-adviser-template.yaml
  thoth/adviser/cli.py
Labels: approved, size/XS

#230 Automatic update of dependency thoth-common from 0.8.3 to 0.8.4
  Pipfile.lock
Labels: bot

#232 Automatic update of dependency thoth-common from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#234 Automatic update of dependency pytest from 4.4.0 to 4.4.1
  Pipfile.lock
Labels: bot

#237 Automatic update of dependency thoth-storages from 0.9.7 to 0.10.0
  Pipfile.lock
Labels: bot

#239 Do not depend on specific graph adapter from specific module
  thoth/adviser/python/bin/dependency_graph.py
  thoth/adviser/python/solver.py
Labels: approved, size/XS

#242 Adjust Dependency Monkey to use Dgraph
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/S

#244 Adjust adviser template to use Dgraph
  openshift/job-adviser-template.yaml
Labels: size/S

#241 Remove JanusGraph specific bits in comments
  openshift/job-adviser-template.yaml
Labels: approved, size/S

#243 Adjust provenance-checker template to use Dgraph
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/S

#238 Remove JanusGraph specific bits
  README.rst
  docs/source/libdependency_graph.rst
Labels: approved, size/S

#236 Trigger graph-sync of dependency-monkey reports into graph
  openshift/job-dependencyMonkey-template.yaml
Labels: size/XS

#235 Added the method to read version from project library to conf.py
  setup.py
Labels: approved, size/M, size/S, size/XS

#245 Automatic update of dependency thoth-storages from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot

#240 Remove is_solvable flag as done in Dgraph implementation
  thoth/adviser/cli.py
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved, size/S, size/XS
