Repository thoth-station/adviser, pull requests merged in 2019-07, with the labels that each got.

#304 Use only packages with known index
  tests/graph_mock.py
  thoth/adviser/python/solver.py
Labels: approved, size/XS

#305 Print out estimated number of stacks in scientific form
  thoth/adviser/python/pipeline/pipeline.py
Labels: size/XS

#306 Report packages forming a found stack inside to a log
  thoth/adviser/python/pipeline/stack_candidates.py
Labels: size/S

#298 Automatic update of dependency thoth-storages from 0.11.4 to 0.14.1
  Pipfile.lock
Labels: bot

#312 added the standard github configuration and a CODEOWNERS file
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/M

#313 Introduce routines for iterating over develop and non-develop deps
  tests/python/pipeline/test_step_context.py
  thoth/adviser/python/pipeline/step_context.py
Labels: size/L

#314 Report error if no recommendation was produced
  thoth/adviser/cli.py
Labels: size/S

#315 Introduce observation reduction step to reduce subgraphs with no observations
  tests/python/pipeline/steps/test_observation_reduction.py
  thoth/adviser/python/builder.py
  thoth/adviser/python/dependency_graph/adaptation/graph.py
  thoth/adviser/python/dependency_graph/adaptation/transaction.py
  thoth/adviser/python/pipeline/step_context.py
  thoth/adviser/python/pipeline/steps/__init__.py
  thoth/adviser/python/pipeline/steps/observation_reduction.py
Labels: size/L

#319 Fix transitive query - correctly propagate runtime information
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved, size/XS

#320 Automatic update of dependency thoth-storages from 0.14.8 to 0.15.0
  Pipfile.lock
Labels: bot

#318 Improve warning message
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved, size/XS

#321 Remove invalid configuration entry APP_FILE in build config
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#323 Automatic update of dependency thoth-storages from 0.15.0 to 0.15.1
  Pipfile.lock
Labels: bot

#324 Automatic update of dependency thoth-solver from 1.2.1 to 1.2.2
  Pipfile.lock
Labels: bot

#325 Automatic update of dependency thoth-python from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#322 Inform user that the missing release will be analyzed later on
  thoth/adviser/cli.py
Labels: approved, size/XS

#326 Automatic update of dependency thoth-storages from 0.15.1 to 0.15.2
  Pipfile.lock
Labels: bot

#330 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#331 Fix handling of additional pytest arguments in setup.py test
  setup.py
Labels: approved, size/S, size/XS

#332 Automatic update of dependency thoth-storages from 0.15.2 to 0.16.0
  Pipfile.lock
Labels: bot

#327 Optimize instantiation of objects when resolved from graph database
  thoth/adviser/python/solver.py
Labels: approved, size/M

#333 Deinstantiate solver once it is no longer needed
  thoth/adviser/python/pipeline/pipeline.py
Labels: approved, size/XS

#328 Optimize retrieval of transitive dependencies to avoid list copies
  tests/python/dependency_graph/test_adaptation.py
  tests/python/pipeline/steps/test_buildtime_error.py
  tests/python/pipeline/steps/test_cve.py
  tests/python/pipeline/steps/test_limit_latest_versions.py
  tests/python/pipeline/steps/test_observation_reduction.py
  tests/python/pipeline/steps/test_performance_adjustment.py
  tests/python/pipeline/steps/test_prereleases.py
  tests/python/pipeline/steps/test_restrict_indexes.py
  tests/python/pipeline/steps/test_toolchain.py
  tests/python/pipeline/steps/test_unreachable.py
  tests/python/pipeline/test_pipeline.py
  tests/python/pipeline/test_step_context.py
  thoth/adviser/python/dependency_graph/adaptation/graph.py
  thoth/adviser/python/pipeline/pipeline.py
  thoth/adviser/python/pipeline/step_context.py
Labels: approved, size/L, size/S, size/XXL

#334 Automatic update of dependency thoth-storages from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot

#336 Release of version 0.5.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/M

#337 Automatic update of dependency thoth-storages from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: bot
