Repository thoth-station/adviser, pull requests merged in 2019-12, with the labels that each got.

#547 Automatic update of dependency hypothesis from 4.50.2 to 4.50.3
  Pipfile.lock
Labels: bot, size/M

#548 Automatic update of dependency hypothesis from 4.50.3 to 4.50.4
  Pipfile.lock
Labels: bot, size/S

#549 Automatic update of dependency hypothesis from 4.50.4 to 4.50.5
  Pipfile.lock
Labels: bot, size/XS

#550 Automatic update of dependency hypothesis from 4.50.5 to 4.50.6
  Pipfile.lock
Labels: bot, size/XS

#552 Use backtracking to run steps
  tests/test_beam.py
  tests/test_context.py
  tests/test_resolver.py
  thoth/adviser/beam.py
  thoth/adviser/context.py
  thoth/adviser/resolver.py
  thoth/adviser/state.py
  thoth/adviser/step.py
Labels: approved, size/XL

#553 Step should not return Nan/Inf
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#555 Remove unused method
  thoth/adviser/resolver.py
Labels: approved, size/M

#557 Log package version before pipeline step execution
  thoth/adviser/resolver.py
Labels: approved, size/XS

#554 Test simulated annealing primitives, refactor core annealing part
  tests/predictors/test_annealing.py
  thoth/adviser/predictors/annealing.py
Labels: size/L

#558 Minor changes to source code
  Pipfile
  Pipfile.lock
  docs/source/predictor.rst
  requirements.txt
  tests/conftest.py
  tests/test_beam.py
  tests/test_context.py
  tests/test_pipeline_builder.py
  tests/test_product.py
  tests/test_report.py
  tests/test_resolver.py
  tests/test_state.py
  tests/units/sieves.py
  thoth/adviser/beam.py
  thoth/adviser/cli.py
  thoth/adviser/context.py
  thoth/adviser/dependency_monkey.py
  thoth/adviser/dm_report.py
  thoth/adviser/exceptions.py
  thoth/adviser/pipeline_builder.py
  thoth/adviser/product.py
  thoth/adviser/report.py
  thoth/adviser/resolver.py
  thoth/adviser/sieve.py
  thoth/adviser/sieves/index_enabled.py
  thoth/adviser/sieves/prereleases.py
  thoth/adviser/sieves/solved.py
  thoth/adviser/state.py
  thoth/adviser/steps/cve.py
Labels: approved, size/XL

#560 Fix boot docstring
  thoth/adviser/boot.py
Labels: approved, size/XS

#561 Fix stride signature
  thoth/adviser/stride.py
Labels: approved, size/XS

#562 Some docs for readers and developers
  docs/source/_static/history_one_found.png
  docs/source/_static/state_space.png
  docs/source/_static/state_space_guided.png
  docs/source/_static/state_space_interpolated.png
  docs/source/_static/state_space_spikes.png
  docs/source/annealing.rst
  docs/source/boots.rst
  docs/source/compatibility.rst
  docs/source/conf.py
  docs/source/dependency_monkey.rst
  docs/source/index.rst
  docs/source/introduction.rst
  docs/source/performance.rst
  docs/source/pipeline.rst
  docs/source/predictor.rst
  docs/source/resolver.rst
  docs/source/sieves.rst
  docs/source/steps.rst
  docs/source/strides.rst
  docs/source/unit.rst
  docs/source/wraps.rst
  tests/predictors/test_annealing.py
  tests/test_beam.py
  tests/test_resolver.py
  thoth/adviser/beam.py
  thoth/adviser/predictor.py
  thoth/adviser/predictors/annealing.py
  thoth/adviser/resolver.py
Labels: approved, size/XXL

#563 Set beam width template in the adviser template job
  openshift/job-adviser-template.yaml
Labels: approved, size/XS

#519 Give more information dependencies were not resolved
  thoth/adviser/exceptions.py
  thoth/adviser/resolver.py
  thoth/adviser/run.py
Labels: approved, size/M

#566 Automatic update of dependency hypothesis from 4.50.6 to 4.50.7
  Pipfile.lock
Labels: bot, size/M

#568 Release of version 0.7.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/XL

#565 Graph cache is not used anymore
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#571 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#572 Automatic update of dependency thoth-solver from 1.4.0 to 1.4.1
  Pipfile.lock
Labels: bot, size/S

#573 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/XS

#574 Automatic update of dependency hypothesis from 4.50.7 to 4.50.8
  Pipfile.lock
Labels: bot, size/S

#570 Fix reference to sieve in docs
  docs/source/sieves.rst
Labels: approved, size/XS

#575 Propagate information about package that has CVE to justification in CVE step
  thoth/adviser/steps/cve.py
Labels: approved, size/XS

#569 Fix references to the source code
  docs/source/unit.rst
Labels: approved, size/XS

#576 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/M

#578 Produce more descriptive message if any of direct dependencies was not resolved
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#577 Adjust parameters for adviser and dependency-monkey
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/S

#582 Do not show not relevant logs to users
  openshift/job-adviser-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/XS

#581 Point to source code documentation for described methods
  docs/source/resolver.rst
Labels: approved, size/M

#580 Fix exit code propagation of the forked child
  thoth/adviser/cli.py
  thoth/adviser/run.py
Labels: approved, size/XS

#564 Minor updates in docs
  README.rst
Labels: size/XS

#579 Add validation of count and limit resolver attributes
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#584 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#586 Point documentation to other libraries
  docs/source/index.rst
Labels: approved, size/XS

#588 Remove graph cache bits no longer used
  .s2i/bin/assemble
Labels: approved, size/S

#583 No need to clone a state before running steps
  docs/source/steps.rst
  thoth/adviser/resolver.py
Labels: approved, size/S

#589 Automatic update of dependency hypothesis from 4.50.8 to 4.51.0
  Pipfile.lock
Labels: bot, size/S

#590 Automatic update of dependency hypothesis from 4.51.0 to 4.51.1
  Pipfile.lock
Labels: bot, size/S

#591 Automatic update of dependency hypothesis from 4.51.1 to 4.52.0
  Pipfile.lock
Labels: bot, size/XS

#592 Automatic update of dependency hypothesis from 4.52.0 to 4.53.0
  Pipfile.lock
Labels: bot, size/XS

#593 Automatic update of dependency hypothesis from 4.53.0 to 4.53.1
  Pipfile.lock
Labels: bot, size/XS

#596 Fix issue when there are no unresolved dependencies left in the state
  thoth/adviser/resolver.py
Labels: size/XS

#595 Document beam width and how to plot it
  docs/source/_static/beam_history_plot.png
  docs/source/pipeline.rst
Labels: size/M

#594 Log correct file location for beam history plots
  thoth/adviser/beam.py
Labels: size/XS

#587 Document pipeline configuration instrumentation
  docs/source/pipeline.rst
Labels: size/M

#585 Add developer's guide to documentation
  docs/source/developers_guide.rst
  docs/source/index.rst
Labels: size/L

#618 Adjust docs for limit latest versions
  docs/source/sieves.rst
Labels: size/XS

#619 Add new iteration method for sieves and steps
  docs/source/developers_guide.rst
  docs/source/sieves.rst
  docs/source/steps.rst
  tests/test_pipeline_config.py
  thoth/adviser/pipeline_config.py
  thoth/adviser/predictor.py
  thoth/adviser/sieve.py
  thoth/adviser/step.py
Labels: approved, size/M

#621 Fork only in the cluster
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  thoth/adviser/run.py
Labels: approved, size/M

#622 Automatic update of dependency hypothesis from 4.53.1 to 4.53.2
  Pipfile.lock
Labels: approved, bot, size/M

#623 Implement a dropout step
  tests/steps/test_dropout.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/dropout.py
Labels: approved, size/L

#626 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/S

#628 Automatic update of dependency hypothesis from 4.53.2 to 4.53.3
  Pipfile.lock
Labels: bot, size/M

#629 Automatic update of dependency hypothesis from 4.53.3 to 4.54.0
  Pipfile.lock
Labels: bot, size/XS

#630 Make temperature function a function of iteration as well
  tests/predictors/test_annealing.py
  thoth/adviser/predictors/annealing.py
Labels: approved, size/M

#625 Keep beam in context
  tests/test_context.py
  thoth/adviser/context.py
  thoth/adviser/resolver.py
Labels: approved, size/XS

#631 Revert "Add new iteration method for sieves and steps"
  docs/source/developers_guide.rst
  docs/source/sieves.rst
  docs/source/steps.rst
  tests/test_pipeline_config.py
  thoth/adviser/pipeline_config.py
  thoth/adviser/predictor.py
  thoth/adviser/sieve.py
  thoth/adviser/step.py
Labels: approved, size/M

#620 Keep track of dependencies added
  tests/test_context.py
  thoth/adviser/context.py
  thoth/adviser/predictor.py
  thoth/adviser/resolver.py
Labels: size/M

#633 Automatic update of dependency hypothesis from 4.54.0 to 4.54.1
  Pipfile.lock
Labels: bot, size/S

#634 Automatic update of dependency hypothesis from 4.54.1 to 4.54.2
  Pipfile.lock
Labels: bot, size/S

#636 Simplify creation of initial states
  thoth/adviser/resolver.py
Labels: size/S

#635 Adjust relative order for steps registration
  thoth/adviser/steps/__init__.py
Labels: size/XS

#637 Fix computing top state in the beam
  thoth/adviser/beam.py
Labels: approved, size/XS

#640 Log also beam size
  tests/predictors/test_annealing.py
  thoth/adviser/predictors/annealing.py
Labels: size/XS

#638 Automatic update of dependency hypothesis from 4.54.2 to 4.55.0
  Pipfile.lock
Labels: bot, size/S

#641 Fix logging format expansion
  thoth/adviser/resolver.py
Labels: size/XS

#632 Do not retrieve markers during resolution
  tests/conftest.py
  tests/test_context.py
  tests/test_product.py
  tests/test_resolver.py
  thoth/adviser/context.py
  thoth/adviser/product.py
  thoth/adviser/resolver.py
Labels: size/L

#643 Automatic update of dependency hypothesis from 4.55.0 to 4.55.1
  Pipfile.lock
Labels: bot, size/XS

#642 Log warning about shared dependencies in the dependency graph
  docs/source/compatibility.rst
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: size/M

#644 Automatic update of dependency hypothesis from 4.55.1 to 4.55.2
  Pipfile.lock
Labels: bot, size/S

#645 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/XS

#639 Improve multi-key sorting of states in the beam
  tests/test_beam.py
  tests/test_resolver.py
  thoth/adviser/beam.py
  thoth/adviser/resolver.py
  thoth/adviser/state.py
Labels: approved, size/L

#646 added an Argo Workflow to run an advise
  openshift/workflow-adviser-template.yaml
Labels: approved, size/L

#649 Register CVE step only for STABLE and TESTING recommendation types
  thoth/adviser/steps/cve.py
Labels: approved, size/S

#648 Automatically choose the most appropriate predictor based on CLI
  thoth/adviser/cli.py
Labels: approved, size/S

#650 Add checks for special cases when environment markers apply to leaf nodes
  thoth/adviser/resolver.py
Labels: approved, size/S

#652 Automatic update of dependency hypothesis from 4.55.2 to 4.55.3
  Pipfile.lock
Labels: bot, size/M

#653 Automatic update of dependency hypothesis from 4.55.3 to 4.55.4
  Pipfile.lock
Labels: bot, size/XS

#654 Automatic update of dependency hypothesis from 4.55.4 to 4.56.0
  Pipfile.lock
Labels: bot, size/M

#655 Automatic update of dependency hypothesis from 4.56.0 to 4.56.1
  Pipfile.lock
Labels: bot, size/XS

#660 Add tests for leaf node expansion with marker set to False
  tests/test_resolver.py
Labels: size/M

#661 Automatic update of dependency hypothesis from 4.56.1 to 4.56.2
  Pipfile.lock
Labels: bot, size/L

#662 Automatic update of dependency hypothesis from 4.56.2 to 4.56.3
  Pipfile.lock
Labels: bot, size/XS

#663 Automatic update of dependency hypothesis from 4.56.3 to 4.57.0
  Pipfile.lock
Labels: bot, size/L

#664 Automatic update of dependency hypothesis from 4.57.0 to 4.57.1
  Pipfile.lock
Labels: bot, size/XS

#665 Automatic update of dependency hypothesis-auto from 1.1.2 to 1.1.3
  Pipfile.lock
Labels: bot, size/M
