Repository thoth-station/adviser, pull requests merged in 2020-04, with the labels that each got.

#896 consistency in openshift templates to run provenance
  openshift/job-provenanceChecker-template.yaml
Labels: approved

#899 Remove unusued parameter
  workflows/templates/advise-template.yaml
Labels: approved

#898 Re-enable fext for beam's internal state handling
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/adviser/beam.py
Labels: approved, size/L

#900 Fix info message causing issues when the beam is empty
  thoth/adviser/resolver.py
Labels: approved, size/XS

#893 Prioritize releases by AICoE
  tests/steps/test_aicoe.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/aicoe.py
Labels: size/L

#904 Release of version 0.9.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/M

#905 Fix bug causing adviser halt for shared resolved packages
  thoth/adviser/resolver.py
Labels: approved

#907 Release of version 0.9.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/XS

#908 Adjust parameters in deployment
  openshift/adviser-template.yaml
  openshift/job-adviser-template.yaml
  workflows/templates/advise-template.yaml
Labels: approved, size/M

#909 Tweak temperature function for ASA, TD and MCTS
  tests/predictors/test_mcts.py
  tests/predictors/test_td.py
  thoth/adviser/predictors/annealing.py
  thoth/adviser/predictors/mcts.py
  thoth/adviser/predictors/td.py
Labels: approved, size/M

#911 Release of version 0.9.2
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/XS

#914 Recommendation type is not lowercase
  app.sh
Labels: approved, size/XS

#915 Improve message when adviser is stopped based on CPU time
  thoth/adviser/resolver.py
Labels: approved, size/XS

#916 Reduce beam width to address OOM issues for large stacks in the cluster
  openshift/adviser-template.yaml
  openshift/job-adviser-template.yaml
  workflows/templates/advise-template.yaml
Labels: approved, size/S

#917 Adjust the message produced
  tests/boots/test_python_version.py
  thoth/adviser/boots/python_version.py
Labels: approved, size/XS

#918 Automatic update of dependency pytest-mypy from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot, size/L

#919 Setup workflow TTL strategy to reduce preassure causing OOM
  openshift/adviser-template.yaml
Labels: approved, size/XS

#920 Introduce heat up phase for the latest predictor
  tests/predictors/test_latest.py
  thoth/adviser/predictors/latest.py
Labels: approved, size/L

#912 Release of version 0.9.3
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, bug, size/XXL

#923 Release of version 0.9.4
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/XS

#926 Liveness wfs
  app.sh
  workflows/templates/advise-template.yaml
Labels: approved, size/S

#927 Fix liveness probe
  workflows/templates/advise-template.yaml
Labels: approved, size/XS

#929 consistency in workflow while using secrets
  workflows/templates/advise-template.yaml
Labels: approved, size/XS

#931 Automatic update of dependency hypothesis from 5.8.0 to 5.8.1
  Pipfile.lock
Labels: bot, size/L

#932 Automatic update of dependency hypothesis from 5.8.1 to 5.8.2
  Pipfile.lock
Labels: bot, size/XS

#933 Automatic update of dependency hypothesis from 5.8.2 to 5.8.3
  Pipfile.lock
Labels: bot, size/M

#930 Fixed readme link
  README.rst
Labels: approved, size/XS

#934 Create a wrap for Intel's MKL env variable configuration
  tests/wraps/test_mkl_threads.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/mkl_threads.py
Labels: approved, size/L

#935 Automatic update of dependency hypothesis from 5.8.3 to 5.8.4
  Pipfile.lock
Labels: bot, size/S

#936 Automatic update of dependency hypothesis from 5.8.4 to 5.8.5
  Pipfile.lock
Labels: bot, size/XS

#937 Automatic update of dependency hypothesis from 5.8.5 to 5.8.6
  Pipfile.lock
Labels: bot, size/XS

#938 Automatic update of dependency hypothesis from 5.8.6 to 5.9.0
  Pipfile.lock
Labels: bot, size/XS

#925 fixed the apiVersion of all the OpenShift Templates
  openshift/adviser-template.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/S

#939 Automatic update of dependency hypothesis from 5.9.0 to 5.9.1
  Pipfile.lock
Labels: bot, size/XS

#941 Automatic update of dependency hypothesis from 5.9.1 to 5.10.0
  Pipfile.lock
Labels: bot, size/M

#940 Handle exit code regardless core file is produced
  thoth/adviser/run.py
Labels: approved, size/XS

#944 intel-tensorflow is built with MKL support
  thoth/adviser/wraps/mkl_threads.py
Labels: approved, size/S

#951 Adviser Dev env var added to template
  openshift/adviser-template.yaml
Labels: approved, size/XS

#948 Implement platform boot
  Pipfile.lock
  tests/boots/test_platform.py
  tests/test_product.py
  tests/test_resolver.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/platform.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#945 Include MKL warning also in dependency monkey runs
  thoth/adviser/wraps/mkl_threads.py
Labels: approved, size/XS
