Repository thoth-station/adviser, pull requests merged in 2020-08, with the labels that each got.

#1093 Add a pipeline unit for suggesting Intel TensorFlow builds
  tests/wraps/test_intel_tensorflow.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/intel_tensorflow.py
Labels: approved, size/L

#1102 Automatic update of dependency hypothesis from 5.23.8 to 5.23.9
  Pipfile.lock
Labels: approved, bot, size/M

#1103 updated document with ceph deployment name specification
  docs/source/developers_guide.rst
Labels: approved, size/S

#1104 Automatic update of dependency hypothesis from 5.23.9 to 5.23.11
  Pipfile.lock
Labels: approved, bot, size/S

#1105 Add docs for RL based predictors
  docs/source/index.rst
  docs/source/introduction.rst
  docs/source/predictors/rl.rst
Labels: approved, size/M

#1107 Automatic update of dependency hypothesis from 5.23.11 to 5.24.0
  Pipfile.lock
Labels: approved, bot, size/S

#1109 Adjust message when resolver does not find any stack
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#1110 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/S

#1113 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.1
  Pipfile.lock
Labels: approved, bot, size/M

#1114 Automatic update of dependency matplotlib from 3.3.0 to 3.3.1
  Pipfile.lock
Labels: approved, bot, size/M

#1118 Release of version 0.14.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1117 Automatic update of dependency hypothesis from 5.24.0 to 5.26.0
  Pipfile.lock
Labels: approved, bot, size/S

#1119 Introduce a stride for discarding non-unique stacks
  tests/strides/test_unique_stack.py
  thoth/adviser/strides/__init__.py
  thoth/adviser/strides/unique_stack.py
Labels: approved, size/L

#1121 Automatic update of dependency thoth-storages from 0.25.1 to 0.25.2
  Pipfile.lock
Labels: approved, bot, size/M

#1122 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/M

#1120 Fix f-string expansion in exception
  thoth/adviser/pipeline_builder.py
Labels: approved, size/XS

#1123 Automatic update of dependency hypothesis from 5.26.0 to 5.27.0
  Pipfile.lock
Labels: approved, bot, size/M

#1129 Automatic update of dependency attrs from 19.3.0 to 20.1.0
  Pipfile.lock
Labels: approved, bot, size/M

#1130 Automatic update of dependency thoth-storages from 0.25.2 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/M

#1131 Automatic update of dependency hypothesis from 5.27.0 to 5.28.0
  Pipfile.lock
Labels: approved, bot, size/M

#1132 Automatic update of dependency pytest-mypy from 0.6.2 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/M

#1133 Automatic update of dependency hypothesis from 5.27.0 to 5.28.0
  Pipfile.lock
Labels: approved, bot, size/S

#1137 Automatic update of dependency hypothesis from 5.28.0 to 5.29.0
  Pipfile.lock
Labels: approved, bot, size/S

#1136 Fix handling of return code when using os.waitpid
  thoth/adviser/run.py
Labels: approved, size/XS

#1138 Fix detection of OOM when os.waitpid is used
  thoth/adviser/run.py
Labels: approved, size/XS

#1140 Release of version 0.14.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1108 add security indicator step
  tests/steps/test_security_indicators.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/L

#1142 Fix performance recommendation name
  tests/steps/test_security_indicators.py
  thoth/adviser/steps/security_indicators.py
Labels: size/S

#1144 Release of version 0.15.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1146 Fix SI step inclusion
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/XS

#1150 Automatic update of dependency hypothesis from 5.29.0 to 5.29.1
  Pipfile.lock
Labels: approved, bot, size/M

#1151 Relock dependencies due to Pipenv/Kebechet bug
  Pipfile.lock
Labels: size/M

#1149 Release of version 0.15.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/XS

#1152 Automatic update of dependency hypothesis from 5.29.3 to 5.29.4
  Pipfile.lock
Labels: approved, bot, size/L

#1153 Automatic update of dependency hypothesis from 5.29.4 to 5.30.0
  Pipfile.lock
Labels: approved, bot, size/S

#1155 Apply limit of stacks only for the accepted stacks
  thoth/adviser/resolver.py
Labels: approved, size/XS
