Repository thoth-station/adviser, pull requests merged in 2020-07, with the labels that each got.

#1042 Introduce a wrap for recommending Python3.8 on RHEL 8.2
  tests/wraps/test_no_semantic_interposition.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/no_semantic_interposition.py
Labels: approved

#913 Disable provenance checks
  openshift/buildConfig-template.yaml
Labels: approved, human_intervention_required, size/XS

#1043 Automatic update of dependency hypothesis from 5.18.3 to 5.19.0
  Pipfile.lock
Labels: approved, bot, size/M

#1020 Implement a pipeline step for recommending AVX2 builds of AICoE Tenso…
  tests/steps/test_tensorflow_avx2.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tensorflow_avx2.py
Labels: approved, size/L

#901 Introduce a mock score step for experimenting with predictors
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/mock_score.py
Labels: approved, size/M

#1045 Add link to Provenance Checks
  README.rst
Labels: approved, size/XS

#1046 Remove tempalates handled by thoth-application
  openshift/adviser-template.yaml
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  workflows/templates/advise-template.yaml
  workflows/templates/kebechet-run-results.yaml
  workflows/templates/trigger-integration-template.yaml
Labels: approved, size/XXL

#1047 Document Wrap pipeline unit type
  docs/source/boots.rst
  docs/source/unit.rst
  docs/source/wraps.rst
Labels: approved, size/M

#1048 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/L

#1051 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/M

#1054 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/M

#1055 Automatic update of dependency hypothesis from 5.19.0 to 5.19.3
  Pipfile.lock
Labels: approved, bot, size/M

#1056 Release of version 0.12.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/XXL

#1057 Remove latest versions limitation
  .thothTemplate.yaml
Labels: size/XS

#1050 Introduce a sieve to filter out incompatible setuptools for Python 3.6
  tests/sieves/test_py36_setuptools.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/py36_setuptools.py
Labels: approved, size/L

#1058 Extend recommendation types
  thoth/adviser/cli.py
  thoth/adviser/enums.py
Labels: size/XS

#1064 Fix pre-commit complains
  tests/boots/backports/test_enum34.py
  tests/boots/backports/test_importlib_metadata.py
  tests/boots/backports/test_importlib_resources.py
  tests/boots/backports/test_mock.py
  tests/sieves/test_py36_setuptools.py
  thoth/adviser/boots/backports/enum34.py
  thoth/adviser/boots/backports/importlib_metadata.py
  thoth/adviser/boots/backports/importlib_resources.py
  thoth/adviser/boots/backports/mock.py
  thoth/adviser/sieves/py36_setuptools.py
Labels: size/L

#1069 Add information about backports to stack info
  tests/boots/backports/test_enum34.py
  tests/boots/backports/test_importlib_metadata.py
  tests/boots/backports/test_importlib_resources.py
  tests/boots/backports/test_mock.py
  thoth/adviser/boots/backports/enum34.py
  thoth/adviser/boots/backports/importlib_metadata.py
  thoth/adviser/boots/backports/importlib_resources.py
  thoth/adviser/boots/backports/mock.py
Labels: approved, size/M

#1070 State aicoe and upstream specific build info for TensorFlow
  docs/source/performance.rst
Labels: approved, size/XS

#1065 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#1068 Automatic update of dependency hypothesis from 5.19.3 to 5.20.2
  Pipfile.lock
Labels: approved, bot, size/M

#1067 Automatic update of dependency matplotlib from 3.2.2 to 3.3.0
  Pipfile.lock
Labels: bot, size/M

#1066 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: bot, size/M

#1073 Automatic update of dependency hypothesis from 5.20.2 to 5.20.3
  Pipfile.lock
Labels: approved, bot, size/XS

#1074 Stack information is never None
  thoth/adviser/boots/python_version.py
  thoth/adviser/context.py
Labels: size/XS

#1072 Add capability of skipping removing a library from an application stack
  docs/source/sieves.rst
  tests/test_resolver.py
  thoth/adviser/exceptions.py
  thoth/adviser/resolver.py
Labels: size/L

#1080 Automatic update of dependency hypothesis from 5.20.3 to 5.21.0
  Pipfile.lock
Labels: approved, bot, size/M

#1078 Rename to PERFORMANCE and SECURITY
  thoth/adviser/cli.py
  thoth/adviser/enums.py
Labels: approved, size/XS

#1075 Document how to do unit placement in modules
  docs/source/unit.rst
Labels: size/M

#1081 Turn backport boots into sieves to run also on transitive dependencies
  setup.py
  tests/sieves/backports/__init__.py
  tests/sieves/backports/test_enum34.py
  tests/sieves/backports/test_functools32.py
  tests/sieves/backports/test_importlib_metadata.py
  tests/sieves/backports/test_importlib_resources.py
  tests/sieves/backports/test_mock.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/backports/__init__.py
  thoth/adviser/sieves/backports/enum34.py
  thoth/adviser/sieves/backports/functools32.py
  thoth/adviser/sieves/backports/importlib_metadata.py
  thoth/adviser/sieves/backports/importlib_resources.py
  thoth/adviser/sieves/backports/mock.py
Labels: size/XL

#1084 Add Kevin to owners section
  OWNERS
Labels: approved, size/XS

#1083 Turn skip package to debug message
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1085 Automatic update of dependency hypothesis from 5.21.0 to 5.23.3
  Pipfile.lock
Labels: approved, bot, size/L

#1082 Add docs to pipeline units and their usage
  docs/source/unit.rst
Labels: approved, size/M

#1089 Automatic update of dependency pytest from 5.4.3 to 6.0.0
  Pipfile.lock
Labels: approved, bot, size/M

#1092 Automatic update of dependency hypothesis from 5.23.3 to 5.23.7
  Pipfile.lock
Labels: approved, bot, size/XS

#1090 Fix selecting dependency monkey predictor based on decision type
  thoth/adviser/cli.py
Labels: approved, size/S

#1094 Automatic update of dependency thoth-storages from 0.24.4 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/M

#1095 Automatic update of dependency thoth-solver from 1.5.2 to 1.6.0
  Pipfile.lock
Labels: approved, bot, size/M

#1096 Automatic update of dependency pytest from 6.0.0 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/M

#1097 Automatic update of dependency hypothesis from 5.23.7 to 5.23.8
  Pipfile.lock
Labels: approved, bot, size/M

#1077 Release of version 0.13.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/XXL
