Repository thoth-station/adviser, pull requests merged in 2020-06, with the labels that each got.

#990 create task trigger integration using workflow-helpers
  openshift/adviser-template.yaml
  workflows/templates/advise-template.yaml
  workflows/templates/finished-webhook-template.yaml
  workflows/templates/trigger-integration-template.yaml
Labels: approved, size/L

#994 correct typo
  workflows/templates/trigger-integration-template.yaml
Labels: approved, size/XS

#976 Filter missing package versions
  tests/graph_mock.py
  tests/test_resolver.py
  thoth/adviser/resolver.py
  thoth/adviser/solver.py
Labels: approved, size/S

#997 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#996 Added pyproject.toml
  .gitignore
  pyproject.toml
Labels: approved, size/XS

#998 Add black as per template project
  pyproject.toml
Labels: approved, size/S

#1005 Do not use OrderedDict for internal state representation
  tests/test_state.py
  thoth/adviser/state.py
Labels: approved, size/M

#1004 Add a boot for tracing memory consumption
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/memtrace.py
Labels: approved, size/L

#1003 Preserve order in pre and post run methods
  docs/source/unit.rst
  thoth/adviser/pipeline_config.py
Labels: approved, size/S

#1006 :Removed unnecessary tempalates
  openshift/adviser-template.yaml
  workflows/templates/kebechet-run-results.yaml
Labels: approved, size/M

#1009 Note down beam width once the resolution is terminated
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1014 Automatic update of dependency thoth-storages from 0.22.12 to 0.23.0
  Pipfile.lock
Labels: bot, size/M

#1019 Dependency relocking to fix CI
  Pipfile.lock
Labels: size/L

#1015 Release of version 0.10.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/M, thoth/human_intervention_required

#1012 Disable setup.py processing in s2i builds
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#1001 Add a check for available platforms
  tests/boots/test_platform.py
  thoth/adviser/boots/platform.py
Labels: approved, size/M

#978 Include each marker of a type just once
  thoth/adviser/product.py
Labels: approved, size/S

#1023 Increase time for SLI
  openshift/adviser-template.yaml
Labels: approved, size/XS

#1021 Remove dependency
  openshift/adviser-template.yaml
Labels: approved, size/XS

#1025 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: bot, size/L

#1030 Automatic update of dependency thoth-storages from 0.23.0 to 0.23.2
  Pipfile.lock
Labels: approved, bot

#1027 Automatic update of dependency matplotlib from 3.2.1 to 3.2.2
  Pipfile.lock
Labels: bot, size/L

#1031 Automatic update of dependency hypothesis from 5.16.1 to 5.16.3
  Pipfile.lock
Labels: approved, bot

#1032 Adjust MANIFEST.in
  MANIFEST.in
Labels: approved

#1036 Automatic update of dependency thoth-storages from 0.23.2 to 0.24.0
  Pipfile.lock
Labels: approved, bot

#1037 Automatic update of dependency hypothesis from 5.16.3 to 5.18.0
  Pipfile.lock
Labels: approved, bot

#1040 Remove provenance-checker job template
  openshift/job-provenanceChecker-template.yaml
Labels: approved

#1041 Automatic update of dependency hypothesis from 5.18.0 to 5.18.3
  Pipfile.lock
Labels: approved, bot
