Repository thoth-station/adviser, pull requests merged in 2020-10, with the labels that each got.

#1413 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/S

#1414 Add images for pipeline and pipeline builder
  docs/source/_static/pipeline.gif
  docs/source/_static/pipeline_builder.gif
Labels: approved, size/XS

#1415 Adjust README file
  MANIFEST.in
  README.rst
Labels: approved, size/L

#1417 Remove voluptuous from dev-packages it is already in packages
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#1418 Fix docstring
  thoth/adviser/step.py
Labels: approved, size/XS

#1419 Adjust compatibility section in docs
  docs/source/compatibility.rst
Labels: approved, size/S

#1420 Fix urls in the integration section
  docs/source/integration.rst
Labels: size/M

#1421 Some units are specific to package, not to package version
  docs/source/unit.rst
  thoth/adviser/pseudonym.py
  thoth/adviser/sieve.py
  thoth/adviser/step.py
  thoth/adviser/unit.py
Labels: size/S

#1416 exclude hc hs if type is secure
  tests/steps/test_security_indicators.py
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/M

#1423 Automatic update of dependency thoth-storages from 0.25.14 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/L

#1424 Automatic update of dependency hypothesis from 5.36.1 to 5.37.0
  Pipfile.lock
Labels: approved, bot, size/L

#1425 Automatic update of dependency pytest from 6.1.0 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/XS

#1429 Fix trailing white space
  docs/source/justifications.rst
Labels: approved, size/S

#1428 Implement package version in configuration for boots, strides and wraps
  tests/conftest.py
  tests/strides/test_one_version.py
  tests/test_pipeline_builder.py
  tests/test_pipeline_config.py
  tests/test_report.py
  tests/test_resolver.py
  tests/units/boots.py
  tests/units/strides.py
  tests/units/wraps.py
  thoth/adviser/pipeline_builder.py
  thoth/adviser/pipeline_config.py
  thoth/adviser/pseudonym.py
  thoth/adviser/resolver.py
  thoth/adviser/sieve.py
  thoth/adviser/step.py
  thoth/adviser/strides/one_version.py
  thoth/adviser/unit.py
Labels: approved, do-not-merge/hold, size/L

#1430 Introduce capability for obtaining units inside a builder context
  tests/test_pipeline_builder.py
  thoth/adviser/pipeline_builder.py
Labels: approved, size/L

#1432 Provide schema for security indicators step so that it is registered
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/S

#1433 Test default configuration schema in units
  tests/base.py
  tests/strides/test_one_version.py
Labels: approved, size/S

#1431 Simplify units implementation based on calling contract
  tests/pseudonyms/test_intel_tensorflow.py
  tests/pseudonyms/test_intel_tensorflow_cpu.py
  tests/sieves/setuptools/test_py36.py
  tests/sieves/tensorflow/test_tf_cuda.py
  tests/wraps/tensorflow/test_mkl_threads.py
  tests/wraps/tensorflow/test_tf_23_accuracy.py
  tests/wraps/tensorflow/test_tf_23_dict_bug.py
  tests/wraps/tensorflow/test_tf_mkl_threads.py
  thoth/adviser/pseudonyms/__init__.py
  thoth/adviser/pseudonyms/intel_tensorflow.py
  thoth/adviser/pseudonyms/intel_tensorflow_cpu.py
  thoth/adviser/sieves/backports/enum34.py
  thoth/adviser/sieves/backports/functools32.py
  thoth/adviser/sieves/backports/importlib_metadata.py
  thoth/adviser/sieves/backports/importlib_resources.py
  thoth/adviser/sieves/backports/mock.py
  thoth/adviser/sieves/pandas/py36_drop.py
  thoth/adviser/sieves/setuptools/py36.py
  thoth/adviser/sieves/tensorflow/tf_cuda.py
  thoth/adviser/steps/tensorflow/tf_113_numpy.py
  thoth/adviser/steps/tensorflow/tf_114_gast.py
  thoth/adviser/steps/tensorflow/tf_21_urllib3.py
  thoth/adviser/steps/tensorflow/tf_22_numpy.py
  thoth/adviser/steps/tensorflow/tf_22_prob.py
  thoth/adviser/steps/tensorflow/tf_avx2.py
  thoth/adviser/steps/tensorflow/tf_rm_scipy.py
  thoth/adviser/wraps/tensorflow/tf_23_accuracy.py
  thoth/adviser/wraps/tensorflow/tf_23_dict_bug.py
  thoth/adviser/wraps/tensorflow/tf_intel.py
  thoth/adviser/wraps/tensorflow/tf_mkl_threads.py
Labels: approved, size/L

#1434 Update docs to reflect package_name in boots, strides and wraps
  docs/source/boots.rst
  docs/source/pipeline.rst
  docs/source/strides.rst
  docs/source/unit.rst
  docs/source/wraps.rst
Labels: approved, size/M

#1435 Remove unused exception
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1440 Automatic update of dependency hypothesis from 5.37.0 to 5.37.1
  Pipfile.lock
Labels: approved, bot, size/M

#1441 Allow null values in pipeline units listing
  thoth/adviser/pipeline_builder.py
Labels: approved, size/S

#1443 Provide probability configuration for assigning a score
  thoth/adviser/steps/_debug/mock_score.py
Labels: approved, size/S

#1442 No need to shrink learnt policy
  tests/predictors/test_mcts.py
  tests/predictors/test_td.py
  thoth/adviser/predictors/mcts.py
  thoth/adviser/predictors/td.py
Labels: approved, size/L

#1445 Units do not need to be stated in the configuration
  thoth/adviser/pipeline_builder.py
Labels: approved, size/S

#1444 Implement n-step TD learning
  tests/predictors/test_td.py
  thoth/adviser/predictors/td.py
  thoth/adviser/steps/_debug/set_score.py
Labels: approved, size/L

#1447 Clear beam history
  thoth/adviser/beam.py
Labels: approved, size/XS

#1448 Register debug units so they can be easily run using supplied conf
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/_debug/__init__.py
Labels: approved, size/XS

#1450 Set score can now generate random score if not explicitly provided
  thoth/adviser/steps/_debug/set_score.py
Labels: size/S

#1451 Allow assigning score when package version or index url is not set
  thoth/adviser/steps/_debug/set_score.py
Labels: size/S

#1449 Deinstantiate solver and let gc do its job
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1446 Plot resolver history
  thoth/adviser/dependency_monkey.py
  thoth/adviser/resolver.py
  thoth/adviser/run.py
Labels: size/M

#1452 Be more accurate with plot label
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1453 Fix message logged
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1454 Make temperature coefficient parametrize and increase it
  thoth/adviser/predictors/annealing.py
Labels: approved, size/XS

#1457 Fix n-step TD-learning
  thoth/adviser/predictors/annealing.py
  thoth/adviser/predictors/td.py
Labels: approved, size/M

#1458 Turn off multi package resolution for debug units
  thoth/adviser/steps/_debug/mock_score.py
  thoth/adviser/steps/_debug/set_score.py
Labels: approved, size/S

#1462 Enable probability assigning score when generating scores
  thoth/adviser/steps/_debug/generate_score.py
Labels: approved, size/S

#1461 Fix assigning score based on probability
  thoth/adviser/steps/_debug/mock_score.py
Labels: approved, size/XS

#1460 Log the highest rated software stack found so far
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1464 Log based on iteration not based on final states produced
  thoth/adviser/resolver.py
Labels: approved, size/S

#1465 Add more weak condition when logging progress
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1466 Keep resolver history only if needed
  thoth/adviser/resolver.py
Labels: approved, size/S

#1468 Document sampling, random walk and hill climbing predictors
  docs/source/_static/hill_climbing.png
  docs/source/_static/random_walk.gif
  docs/source/predictors/hill_climbing.rst
  docs/source/predictors/random_walk.rst
  docs/source/predictors/sampling.rst
Labels: approved, size/M

#1469 Adjust plot labels
  thoth/adviser/beam.py
  thoth/adviser/resolver.py
Labels: approved

#1470 Fix MCTS history keeping
  thoth/adviser/predictors/mcts.py
Labels: approved, size/XS

#1471 Introduce trace parameter to TD learning
  thoth/adviser/predictors/td.py
Labels: approved, size/S

#1463 Switch to TD-learning with step==2 instead of Monte Carlo learning
  thoth/adviser/cli.py
  thoth/adviser/predictor.py
Labels: size/S

#1472 Do one step TD-learning and turn off trace
  thoth/adviser/cli.py
Labels: approved, size/XS

#1473 Use C extension for computing termial random
  Pipfile
  Pipfile.lock
  docs/source/deployment.rst
  tests/test_state.py
  thoth/adviser/cli.py
  thoth/adviser/state.py
Labels: size/XL

#1475 Do not keep history by default
  tests/test_predictor.py
  thoth/adviser/utils.py
Labels: approved, size/S

#1476 Temperature computation and probability does not need to be done for t=0
  tests/predictors/test_td.py
  thoth/adviser/predictors/td.py
Labels: approved, size/M

#1477 Print found stack score to logs
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1480 Fix history kept in TD-learning
  thoth/adviser/predictors/td.py
Labels: approved, size/S

#1479 Add stack info when no stack is produced
  thoth/adviser/boots/version_clash.py
  thoth/adviser/exceptions.py
  thoth/adviser/predictors/td.py
  thoth/adviser/resolver.py
Labels: approved, do-not-merge/hold, size/M

#1481 Improve message logged
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1483 Provide stack info if direct dependencies were not resolved
  thoth/adviser/resolver.py
Labels: size/S

#1484 Point to the existing relevant justification document
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1482 Provide stack info if resolver failed to resolve direct dependencies
  thoth/adviser/exceptions.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#1485 Fix documentation for the package_name option in pseudonyms
  docs/source/pseudonyms.rst
Labels: approved, size/XS

#1490 Add documentation for predictor that uses a gradient based method
  docs/source/predictors/neural_network.rst
Labels: approved, size/M

#1493 Add docs for advising manifest changes
  docs/source/index.rst
  docs/source/manifest_changes.rst
  thoth/adviser/wraps/tensorflow/tf_mkl_threads.py
Labels: size/M

#1497 Fix pre-commit complains
  docs/source/predictors/neural_network.rst
Labels: approved, size/XS

#1498 Remove version clash boot
  tests/boots/test_version_clash.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/version_clash.py
Labels: hacktoberfest-accepted, size/L

#1489 Fix adviser testsuite
  tests/test_resolver.py
Labels: do-not-merge/hold, size/XS

#1496 Call wraps only if products are in the final resolver result
  docs/source/wraps.rst
  tests/test_report.py
  tests/test_resolver.py
  thoth/adviser/report.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#1500 Make multi_package_resolution part of the step unit configuration
  docs/source/steps.rst
  tests/base.py
  tests/steps/test_dropout.py
  tests/test_pipeline_builder.py
  tests/test_pipeline_config.py
  tests/test_resolver.py
  tests/test_step.py
  tests/units/steps.py
  thoth/adviser/resolver.py
  thoth/adviser/step.py
  thoth/adviser/steps/_debug/generate_score.py
  thoth/adviser/steps/_debug/mock_score.py
  thoth/adviser/steps/_debug/set_score.py
  thoth/adviser/steps/aicoe.py
  thoth/adviser/steps/cve.py
  thoth/adviser/steps/dropout.py
  thoth/adviser/steps/security_indicators.py
  thoth/adviser/steps/tensorflow/tf_113_numpy.py
  thoth/adviser/steps/tensorflow/tf_114_gast.py
  thoth/adviser/steps/tensorflow/tf_21_urllib3.py
  thoth/adviser/steps/tensorflow/tf_22_numpy.py
  thoth/adviser/steps/tensorflow/tf_22_prob.py
  thoth/adviser/steps/tensorflow/tf_avx2.py
  thoth/adviser/steps/tensorflow/tf_rm_scipy.py
Labels: approved, size/L

#1499 Automatic update of dependency hypothesis from 5.37.3 to 5.38.1
  Pipfile.lock
Labels: approved, bot, size/XL

#1501 Added documentation to integrate kebechet
  docs/source/integration.rst
Labels: approved, size/M

#1502 Add docs for package combinations predictor
  docs/source/index.rst
  docs/source/predictors/package_combinations.rst
Labels: approved, size/M

#1504 Release of version 0.19.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/L

#1505 Fix trailing whitespace in docs
  docs/source/predictors/package_combinations.rst
Labels: approved, size/XS

#1506 Log message only if relevant
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1507 Minor formatting changes in Kebechet docs
  docs/source/integration.rst
Labels: approved, size/M

#1509 Propagate statistics to the final report
  tests/test_report.py
  thoth/adviser/report.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#1510 Handle cannot produce stack exception so results are not overwritten
  thoth/adviser/run.py
Labels: approved, size/S

#1512 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#1513 Release of version 0.19.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1518 Automatic update of dependency hypothesis from 5.38.1 to 5.39.0
  Pipfile.lock
Labels: approved, bot, size/M
