Repository thoth-station/adviser, pull requests merged in 2020-11, with the labels that each got.

#1521 Automatic update of dependency thoth-storages from 0.25.15 to 0.25.16
  Pipfile.lock
Labels: approved, bot, size/L

#1522 Automatic update of dependency toml from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/L

#1523 Automatic update of dependency hypothesis from 5.39.0 to 5.41.0
  Pipfile.lock
Labels: approved, bot, size/L

#1529 A pipeline unit that suggests not to use h5py>=3 with TF==2.1
  tests/steps/tensorflow/test_tf_21_h5py.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tensorflow/__init__.py
  thoth/adviser/steps/tensorflow/tf_21_h5py.py
Labels: approved, size/L

#1530 Automatic update of dependency hypothesis from 5.41.0 to 5.41.1
  Pipfile.lock
Labels: approved, bot, size/M

#1528 Introduce a sieve for filtering out incompatible TensorFlow for Py3.9
  tests/sieves/tensorflow/test_tf_py39.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/tensorflow/__init__.py
  thoth/adviser/sieves/tensorflow/tf_py39.py
Labels: approved, size/L

#1527 Handle SIGUSR1 handler to stop exploitation phase
  liveness.py
  thoth/adviser/predictors/td.py
Labels: approved, size/M

#1532 Release of version 0.20.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1540 Automatic update of dependency thoth-storages from 0.25.16 to 0.25.17
  Pipfile.lock
Labels: approved, bot, size/S

#1542 Add a temporary workaround for #1541
  thoth/adviser/beam.py
Labels: approved, size/XS

#1538 Adjust message logged to reduce confusion
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1535 Adjust description in liveness.py
  liveness.py
Labels: approved, size/S

#1536 Fix issue when signal is sent in one call in livenenss.py
  liveness.py
Labels: approved, size/S

#1537 Increase verbosity to see where inspections are triggered
  thoth/adviser/dependency_monkey.py
Labels: size/XS

#1539 Provide stack info in security indicators
  tests/steps/test_security_indicators.py
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/M

#1548 Release of version 0.20.1
  CHANGELOG.md
  tests/test_beam.py
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1544 Automatic update of dependency attrs from 20.2.0 to 20.3.0
  Pipfile.lock
Labels: approved, bot, size/S

#1547 Automatic update of dependency thoth-storages from 0.25.17 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/S

#1554 Automatic update of dependency hypothesis from 5.41.1 to 5.41.2
  Pipfile.lock
Labels: approved, bot, size/M

#1556 Add missing link to user-stack scoring justification
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1559 Add a wrap that notifies about a bug when mutliple instances of TF are running
  tests/wraps/tensorflow/test_tf_38518.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/tensorflow/__init__.py
  thoth/adviser/wraps/tensorflow/tf_38518.py
Labels: approved, size/L

#1562 Automatic update of dependency thoth-storages from 0.26.0 to 0.26.1
  Pipfile.lock
Labels: approved, bot, size/S

#1558 Add a pipeline unit wrap for slow keras embedding layer
  tests/wraps/tensorflow/test_tf_42475.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/tensorflow/__init__.py
  thoth/adviser/wraps/tensorflow/tf_42475.py
Labels: approved, size/L

#1563 Automatic update of dependency matplotlib from 3.3.2 to 3.3.3
  Pipfile.lock
Labels: approved, bot, size/M

#1567 Automatic update of dependency pytest-mypy from 0.7.0 to 0.8.0
  Pipfile.lock
Labels: approved, bot, size/L

#1564 Consider library usage for TF 42475 wrap
  tests/wraps/tensorflow/test_tf_42475.py
  thoth/adviser/wraps/tensorflow/tf_42475.py
Labels: approved, size/S

#1565 Report warning if Python versions do not match
  Pipfile.lock
  tests/boots/test_python_version.py
  thoth/adviser/boots/python_version.py
Labels: approved, size/L

#1570 Match score of the user's stack printed with the final score reported
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1534 Handle exception raised when the given record was not found
  tests/steps/test_security_indicators.py
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/S

#1560 Implement a sieve that filters out TensorFlow releases based on API
  MANIFEST.in
  setup.py
  tests/sieves/tensorflow/test_tf_api.py
  thoth/adviser/data/tensorflow/api.json
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/tensorflow/__init__.py
  thoth/adviser/sieves/tensorflow/tf_api.py
  thoth/adviser/unit.py
Labels: approved, size/XXL

#1569 Improve message logged when reporting resolver's progress
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1578 Release of version 0.21.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1576 h5py==3 causes troubles also on TensorFlow 2.3.1
  tests/steps/tensorflow/test_tf_21_h5py.py
  thoth/adviser/steps/tensorflow/tf_21_h5py.py
Labels: approved, size/S

#1581 Add a warning to TF API
  tests/sieves/tensorflow/test_tf_api.py
  thoth/adviser/sieves/tensorflow/tf_api.py
Labels: approved, size/M

#1584 properly JSON formatted advised manifest changes
  docs/source/manifest_changes.rst
  tests/test_product.py
  tests/wraps/tensorflow/test_mkl_threads.py
  tests/wraps/tensorflow/test_tf_mkl_threads.py
  thoth/adviser/state.py
  thoth/adviser/wraps/tensorflow/tf_mkl_threads.py
Labels: approved, size/M

#1585 Fix pre-commit issues
  tests/test_product.py
Labels: approved, size/M

#1594 Include dependency if at least one lib always requires it
  tests/test_product.py
  thoth/adviser/product.py
Labels: approved, size/L

#1587 Update TensorFlow symbols database
  thoth/adviser/data/tensorflow/api.json
Labels: approved, size/L

#1592 Introduce THOTH_CONFIG_CHECK environment variable
  docs/source/integration.rst
Labels: approved, size/XS

#1590 port to python 38
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: size/L
