Repository thoth-station/adviser, pull requests merged in 2020-02, with the labels that each got.

#790 Automatic update of dependency matplotlib from 3.1.2 to 3.1.3
  Pipfile.lock
Labels: bot, size/M

#791 Automatic update of dependency hypothesis-auto from 1.1.3 to 1.1.4
  Pipfile.lock
Labels: bot, size/XS

#792 Automatic update of dependency hypothesis from 4.57.1 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS

#786 Adjust inner workflow for GitHub App
  openshift/adviser-template.yaml
  openshift/job-adviser-template.yaml
  openshift/workflow-adviser-template.yaml
  workflows/templates/advise-template.yaml
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/XL

#793 Modify parameters for GitHub App
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/XS

#794 Make decision type and recommendation type lowercase
  thoth/adviser/cli.py
Labels: approved, size/XS

#796 Automatic update of dependency hypothesis from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#795 Use correct storage to store results
  openshift/adviser-template.yaml
  workflows/templates/advise-template.yaml
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/XS

#800 Automatic update of dependency hypothesis from 5.4.2 to 5.5.1
  Pipfile.lock
Labels: bot, size/M

#798 Propagate information about missing configuration in report
  thoth/adviser/boots/solved_software_environment.py
Labels: approved, size/M

#797 Add a wrap for adding info about no observations
  tests/wraps/test_no_observation.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/no_onservation.py
Labels: approved, size/L

#801 State thoth-s2i in integration
  docs/source/integration.rst
Labels: approved, size/XS

#781 Log information about future solver runs of unsolved dependencies
  thoth/adviser/run.py
Labels: approved, size/XS

#703 Abi compat sieve
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/abi_compat.py
Labels: approved, size/L

#804 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/M

#803 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#802 abi-compat-sieve tests
  tests/sieves/test_abi_compat.py
Labels: approved, size/M

#807 Add default value when user does not provided Pipfile.lock
  workflows/templates/advise-template.yaml
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/S

#808 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/M

#809 Adjust version and use correct keys
  openshift/adviser-template.yaml
  workflows/templates/advise-template.yaml
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/S

#810 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#811 Automatic update of dependency hypothesis from 5.5.1 to 5.5.2
  Pipfile.lock
Labels: bot, size/XS

#812 No deafult value null for metadata
  openshift/adviser-template.yaml
Labels: approved, size/XS

#813 Automatic update of dependency hypothesis from 5.5.2 to 5.5.3
  Pipfile.lock
Labels: bot, size/M

#814 Automatic update of dependency hypothesis from 5.5.3 to 5.5.4
  Pipfile.lock
Labels: bot, size/XS

#815 Add URLs to GitHub and PyPI
  setup.py
Labels: approved, size/XS

#816 Adviser workflow when using Thamos CLI
  workflows/templates/advise-template.yaml
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/M

#817 Do not overwrite results computed in the forked process
  thoth/adviser/run.py
Labels: approved, size/XS

#818 Child exists with status code 256
  thoth/adviser/run.py
Labels: approved, size/XS

#805 Add templates for releases
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: size/M

#825 Propagate metadata to products
  thoth/adviser/product.py
Labels: size/XS

#824 Allow context to be passed as a file
  thoth/adviser/cli.py
Labels: approved, size/S

#827 Ignore the run logger for dependency monkey runs
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/XS

#823 OpenShift templates are referenced by label
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/XS

#828 Fix test suite
  setup.py
  tests/test_product.py
Labels: approved, size/S

#829 Use the correct condition for checking parameters
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/XS

#830 Propagate the original runtime environment used in resolving in pipel…
  tests/test_product.py
  thoth/adviser/product.py
Labels: approved, size/XS

#831 Solved software environment has to be run after changes to environment
  thoth/adviser/boots/__init__.py
Labels: approved, size/XS
