Repository thoth-station/adviser, pull requests merged in 2020-09, with the labels that each got.

#1154 Log warning about no SI just once per pipeline run
  thoth/adviser/steps/security_indicators.py
Labels: approved, kind/feature, size/S

#1159 Introduce a way to parametrize predictor
  thoth/adviser/cli.py
Labels: approved, size/M

#1162 Fix warnings produced during executing the test suite
  tests/conftest.py
  tests/predictors/test_annealing.py
  tests/predictors/test_hill_climbing.py
  tests/predictors/test_latest.py
  tests/predictors/test_random_walk.py
  tests/predictors/test_sampling.py
Labels: approved, size/M

#1160 Introduce prioritized packages to predictors
  thoth/adviser/predictors/latest.py
  thoth/adviser/predictors/random_walk.py
  thoth/adviser/state.py
Labels: approved, size/M

#1166 Implement a predictor that generates package combinations
  tests/predictors/test_package_combinations.py
  thoth/adviser/predictors/__init__.py
  thoth/adviser/predictors/package_combinations.py
Labels: approved, size/L

#1165 Document raising EagerStopPipeline in predictor
  docs/source/predictor.rst
Labels: approved, size/XS

#1171 Release of version 0.16.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/S

#1170 Automatic update of dependency hypothesis from 5.30.0 to 5.33.1
  Pipfile.lock
Labels: approved, bot, size/L

#1175 Automatic update of dependency attrs from 20.1.0 to 20.2.0
  Pipfile.lock
Labels: approved, bot, size/L

#1179 Automatic update of dependency attrs from 20.1.0 to 20.2.0
  Pipfile.lock
Labels: approved, bot, size/S

#1180 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.6
  Pipfile.lock
Labels: approved, bot, size/S

#1181 Automatic update of dependency hypothesis from 5.33.1 to 5.33.2
  Pipfile.lock
Labels: approved, bot, size/S

#1185 Automatic update of dependency thoth-storages from 0.25.6 to 0.25.7
  Pipfile.lock
Labels: approved, bot, size/M

#1172 Introduce a step prevents from resolving some combinations of urllib3 with TensorFlow=2.1
  tests/steps/test_tensorflow_21_urllib3.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tensorflow_21_urllib3.py
Labels: approved, do-not-merge/hold, size/L

#1186 Automatic update of dependency hypothesis from 5.33.2 to 5.34.1
  Pipfile.lock
Labels: approved, bot, size/S

#1187 Automatic update of dependency hypothesis from 5.33.2 to 5.35.0
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/S

#1177 Provide a link to justification to each pipeline unit
  thoth/adviser/run.py
  thoth/adviser/steps/aicoe.py
  thoth/adviser/steps/security_indicators.py
  thoth/adviser/steps/tensorflow_avx2.py
  thoth/adviser/wraps/intel_tensorflow.py
  thoth/adviser/wraps/mkl_threads.py
  thoth/adviser/wraps/no_onservation.py
  thoth/adviser/wraps/no_semantic_interposition.py
Labels: do-not-merge/hold, size/M

#1192 Automatic update of dependency thoth-storages from 0.25.7 to 0.25.8
  Pipfile.lock
Labels: approved, bot, size/S

#1193 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/XS

#1195 Fix message formatting
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1189 Provide a link to justification to pipeline units
  tests/steps/test_security_indicators.py
  tests/steps/test_tensorflow_avx2.py
  tests/wraps/test_intel_tensorflow.py
  tests/wraps/test_mkl_threads.py
  tests/wraps/test_no_observation.py
  tests/wraps/test_no_semantic_interposition.py
  thoth/adviser/run.py
  thoth/adviser/steps/aicoe.py
  thoth/adviser/steps/security_indicators.py
  thoth/adviser/steps/tensorflow_avx2.py
  thoth/adviser/wraps/intel_tensorflow.py
  thoth/adviser/wraps/mkl_threads.py
  thoth/adviser/wraps/no_onservation.py
  thoth/adviser/wraps/no_semantic_interposition.py
Labels: size/M

#1176 Add an ability to specify manifest changes
  thoth/adviser/state.py
Labels: size/S

#1200 Notify users about accuracy bug when TensorFlow 2.3 is used
  tests/wraps/test_tf_accuracy.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/tf_accuracy.py
Labels: approved, size/L

#1201 Automatic update of dependency matplotlib from 3.3.1 to 3.3.2
  Pipfile.lock
Labels: approved, bot, size/L

#1203 Automatic update of dependency hypothesis from 5.35.0 to 5.35.2
  Pipfile.lock
Labels: approved, bot, size/XS

#1202 Restrict resolutions of tensorflow==2.2 with tensorflow-probability
  tests/steps/test_tf_22_prob.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tf_22_prob.py
Labels: approved, size/L

#1205 Make pre-commit happy
  tests/steps/test_tf_22_prob.py
  thoth/adviser/steps/tensorflow_21_urllib3.py
  thoth/adviser/wraps/tf_accuracy.py
Labels: size/XS

#1209 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.9
  Pipfile.lock
Labels: approved, bot

#1190 Correct messages printed to users
  thoth/adviser/run.py
Labels: size/XS

#1198 Link to justification document when unresolved dependencies
  thoth/adviser/resolver.py
Labels: size/XS

#1206 Extend the tf-probability import error to all tensorflow-packages
  tests/steps/test_tf_22_prob.py
  thoth/adviser/steps/tf_22_prob.py
Labels: size/M

#1199 State manifest changes in the pipeline product
  tests/test_product.py
  thoth/adviser/product.py
Labels: size/M

#1210 Automatic update of dependency hypothesis from 5.35.2 to 5.35.3
  Pipfile.lock
Labels: approved, bot

#1196 Perform copy of the advised manifest changes on state clone
  tests/test_state.py
  thoth/adviser/state.py
Labels: size/XS

#1197 Advise to add OMP_NUM_THREADS environment variable when MKL is used
  Pipfile
  Pipfile.lock
  tests/wraps/test_mkl_threads.py
  thoth/adviser/state.py
  thoth/adviser/wraps/mkl_threads.py
Labels: size/L

#1194 Do not accept stacks with TF 2.1 and urllib3 that cause issues
  tests/steps/test_tensorflow_21_urllib3.py
  thoth/adviser/steps/tensorflow_21_urllib3.py
Labels: needs-rebase, size/M

#1213 Fix typing of advised manifest changes
  thoth/adviser/product.py
Labels: approved, size/XS

#1215 Provide mechanism to verify justification schema
  Pipfile
  Pipfile.lock
  tests/base.py
  tests/steps/tensorflow/test_tf_avx2.py
  tests/steps/test_aicoe.py
  tests/steps/test_cve.py
  tests/steps/test_security_indicators.py
Labels: size/L

#1216 Use cached Python version tuples
  thoth/adviser/sieves/backports/enum34.py
  thoth/adviser/sieves/backports/functools32.py
  thoth/adviser/sieves/backports/importlib_metadata.py
  thoth/adviser/sieves/backports/importlib_resources.py
  thoth/adviser/sieves/backports/mock.py
Labels: size/S

#1217 Implement automatic schema checks in the testsuite
  tests/base.py
  tests/conftest.py
  tests/test_beam.py
  tests/test_product.py
  tests/test_resolver.py
  tests/test_state.py
Labels: approved, size/M

#1218 State is no longer using OrderedDict to gain performance
  tests/conftest.py
  tests/predictors/test_latest.py
  tests/test_product.py
  tests/test_resolver.py
  tests/test_state.py
Labels: approved, size/L

#1219 Be more specific about justification types provided
  tests/base.py
Labels: approved, size/XS

#1221 Rephrase code to make pydocstyle and black happy at the same time
  tests/conftest.py
Labels: size/S

#1222 Fix the testsuite issue
  tests/conftest.py
  tests/test_state.py
Labels: size/S

#1223 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M

#1224 Fix version checks - be accurate about TensorFlow versions
  thoth/adviser/steps/tensorflow/tf_21_urllib3.py
  thoth/adviser/steps/tensorflow/tf_22_prob.py
  thoth/adviser/wraps/tensorflow/tf_23_accuracy.py
  thoth/adviser/wraps/tensorflow/tf_23_dict_bug.py
Labels: approved, size/M

#1227 Release of version 0.17.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/M

#1231 Add test for intel TensorFlow
  tests/wraps/tensorflow/test_tf_intel.py
Labels: approved, size/L

#1233 Link justification for the approximating latest predictor
  thoth/adviser/predictors/latest.py
Labels: approved, size/XS

#1235 Provide justification links to various parts of the resolution process
  thoth/adviser/boots/solved_software_environment.py
  thoth/adviser/resolver.py
  thoth/adviser/run.py
  thoth/adviser/sieves/backports/enum34.py
  thoth/adviser/sieves/backports/functools32.py
  thoth/adviser/sieves/backports/importlib_metadata.py
  thoth/adviser/sieves/backports/importlib_resources.py
  thoth/adviser/sieves/backports/mock.py
  thoth/adviser/steps/cve.py
Labels: approved, size/M

#1232 Link justification documents related to resolver messages
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1236 Add a step to tp correct version of NumPy with TF==1.13.1
  tests/steps/tensorflow/test_tf_113_numpy.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tensorflow/__init__.py
  thoth/adviser/steps/tensorflow/tf_113_numpy.py
Labels: approved, size/L

#1239 Fix wrong import
  thoth/adviser/predictors/latest.py
Labels: approved, size/XS

#1234 Turn warnings into errors reported when AICoE index cannot be parsed
  thoth/adviser/unit.py
Labels: approved, size/XS

#1243 Fix providing justification to CVE step
  thoth/adviser/steps/cve.py
Labels: approved, size/XS

#1245 Fix message printed
  thoth/adviser/resolver.py
  thoth/adviser/run.py
Labels: size/XS

#1248 Automatic update of dependency hypothesis from 5.35.3 to 5.35.4
  Pipfile.lock
Labels: approved, bot, size/S

#1247 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1250 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/XS

#1252 Fix formatting in backports
  thoth/adviser/sieves/backports/enum34.py
  thoth/adviser/sieves/backports/functools32.py
  thoth/adviser/sieves/backports/mock.py
Labels: approved, size/S

#1251 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1240 Add justification links related to user stack scoring
  thoth/adviser/resolver.py
Labels: size/S

#1257 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1258 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1254 Fix pre-commit issues reported
  thoth/adviser/run.py
Labels: approved, size/XS

#1259 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1261 Do not accept CVEs when recommendation type is set to security
  tests/steps/test_cve.py
  thoth/adviser/steps/cve.py
Labels: size/M

#1264 Implement a sieve that drops Pandas>=1.2 on Python 3.6
  setup.py
  tests/sieves/pandas/__init__.py
  tests/sieves/pandas/test_py36_drop.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/pandas/__init__.py
  thoth/adviser/sieves/pandas/py36_drop.py
Labels: approved, size/L

#1265 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/M

#1262 Do not recommend using TensorFlow<2.3>=2.0 with NumPy>=1.19.0
  tests/steps/tensorflow/test_tf_22_numpy.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tensorflow/__init__.py
  thoth/adviser/steps/tensorflow/tf_22_numpy.py
Labels: approved, size/L

#1253 A pipeline step to prevent resolving TF<=1.14 with gast>0.2.2
  tests/steps/tensorflow/test_tf_114_gast.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tensorflow/__init__.py
  thoth/adviser/steps/tensorflow/tf_114_gast.py
Labels: approved, size/L

#1267 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1269 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1270 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1271 Automatic update of dependency hypothesis from 5.35.4 to 5.36.0
  Pipfile.lock
Labels: approved, bot, size/S

#1272 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/S

#1274 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1276 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1273 Add a link to Python version justification
  tests/boots/test_python_version.py
  thoth/adviser/boots/python_version.py
Labels: approved, size/S

#1249 Introduce a step for removing scipy for TF>=2.1<2.3 releases
  tests/steps/tensorflow/test_tf_rm_scipy.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/steps/tensorflow/__init__.py
  thoth/adviser/steps/tensorflow/tf_rm_scipy.py
Labels: approved, size/L

#1238 Add a mechanism to skip packages from a stack based on pipeline steps
  docs/source/sieves.rst
  docs/source/steps.rst
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#1280 Fix complains of pre-commit
  thoth/adviser/steps/tensorflow/tf_rm_scipy.py
Labels: approved, size/XS

#1281 Add stack information in boots
  tests/boots/test_ubi.py
  thoth/adviser/boots/platform.py
  thoth/adviser/boots/python_version.py
  thoth/adviser/boots/rhel_version.py
  thoth/adviser/boots/solved_software_environment.py
  thoth/adviser/boots/ubi.py
Labels: approved, size/M

#1284 Include pre-releases pipeline unit only if pre-releases are disabled
  tests/sieves/test_prereleases.py
  thoth/adviser/sieves/prereleases.py
Labels: approved, size/M

#1287 Provide stack info in step pipeline units
  tests/steps/tensorflow/test_tf_113_numpy.py
  tests/steps/tensorflow/test_tf_21_urllib3.py
  tests/steps/tensorflow/test_tf_22_prob.py
  thoth/adviser/steps/tensorflow/tf_113_numpy.py
  thoth/adviser/steps/tensorflow/tf_114_gast.py
  thoth/adviser/steps/tensorflow/tf_21_urllib3.py
  thoth/adviser/steps/tensorflow/tf_22_numpy.py
  thoth/adviser/steps/tensorflow/tf_22_prob.py
  thoth/adviser/steps/tensorflow/tf_rm_scipy.py
Labels: approved, size/L

#1283 Provide stack info in pipeline sieves
  tests/sieves/pandas/test_py36_drop.py
  tests/sieves/setuptools/test_py36.py
  tests/sieves/test_solved.py
  thoth/adviser/boots/platform.py
  thoth/adviser/boots/solved_software_environment.py
  thoth/adviser/sieves/abi_compat.py
  thoth/adviser/sieves/pandas/py36_drop.py
  thoth/adviser/sieves/setuptools/py36.py
  thoth/adviser/sieves/solved.py
  thoth/adviser/sieves/tensorflow/tf_cuda.py
Labels: approved, do-not-merge/hold, size/L

#1290 Rename sieve to conform naming convention
  tests/sieves/pandas/test_py36_drop.py
  thoth/adviser/sieves/pandas/__init__.py
  thoth/adviser/sieves/pandas/py36_drop.py
Labels: approved, size/S

#1291 Fix black complains
  thoth/adviser/steps/tensorflow/tf_113_numpy.py
  thoth/adviser/steps/tensorflow/tf_114_gast.py
  thoth/adviser/steps/tensorflow/tf_21_urllib3.py
  thoth/adviser/steps/tensorflow/tf_22_numpy.py
  thoth/adviser/steps/tensorflow/tf_22_prob.py
  thoth/adviser/steps/tensorflow/tf_rm_scipy.py
Labels: approved, size/M

#1289 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1294 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1297 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1299 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1300 Release of version 0.18.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, bot, size/M

#1304 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1306 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1307 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1310 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1314 Introduce a base class for implementing pipeline unit tests
  tests/base.py
  tests/boots/test_fully_specified_environment.py
  tests/boots/test_platform.py
  tests/boots/test_python_version.py
  tests/boots/test_rhel_version.py
  tests/boots/test_solved_software_environment.py
  tests/boots/test_ubi.py
  tests/boots/test_version_clash.py
  tests/sieves/backports/test_enum34.py
  tests/sieves/backports/test_functools32.py
  tests/sieves/backports/test_importlib_metadata.py
  tests/sieves/backports/test_importlib_resources.py
  tests/sieves/backports/test_mock.py
  tests/sieves/pandas/test_py36_drop.py
  tests/sieves/setuptools/test_py36.py
  tests/sieves/tensorflow/test_tf_cuda.py
  tests/sieves/test_abi_compat.py
  tests/sieves/test_filter_index.py
  tests/sieves/test_index_enabled.py
  tests/sieves/test_locked.py
  tests/sieves/test_prereleases.py
  tests/sieves/test_solved.py
  tests/sieves/test_version_constraint.py
  tests/steps/tensorflow/test_tf_113_numpy.py
  tests/steps/tensorflow/test_tf_114_gast.py
  tests/steps/tensorflow/test_tf_21_urllib3.py
  tests/steps/tensorflow/test_tf_22_numpy.py
  tests/steps/tensorflow/test_tf_22_prob.py
  tests/steps/tensorflow/test_tf_avx2.py
  tests/steps/tensorflow/test_tf_rm_scipy.py
  tests/steps/test_aicoe.py
  tests/steps/test_cve.py
  tests/steps/test_dropout.py
  tests/steps/test_security_indicators.py
  tests/strides/test_one_version.py
  tests/strides/test_random_decision.py
  tests/strides/test_unique_stack.py
  tests/wraps/python/test_no_semantic_interposition.py
  tests/wraps/tensorflow/test_intel.py
  tests/wraps/tensorflow/test_mkl_threads.py
  tests/wraps/tensorflow/test_tf_23_accuracy.py
  tests/wraps/tensorflow/test_tf_23_dict_bug.py
  tests/wraps/tensorflow/test_tf_intel.py
  tests/wraps/tensorflow/test_tf_mkl_threads.py
  tests/wraps/test_no_observation.py
Labels: approved, size/XL

#1316 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1318 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1319 Automatic update of dependency hypothesis from 5.36.0 to 5.36.1
  Pipfile.lock
Labels: approved, bot, size/S

#1321 Automatic update of dependency hypothesis from 5.36.0 to 5.36.1
  Pipfile.lock
Labels: approved, bot, size/S

#1322 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1323 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1324 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1325 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1326 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1329 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1335 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1336 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1338 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1342 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1345 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1346 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1350 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1354 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1355 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1357 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/S

#1356 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1359 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1361 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1362 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1364 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1365 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1368 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1370 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1371 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1378 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1379 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1313 Introduce Pseudonym pipeline unit type
  docs/source/index.rst
  docs/source/pseudonyms.rst
  setup.py
  tests/base.py
  tests/conftest.py
  tests/helpers.py
  tests/pseudonyms/__init__.py
  tests/pseudonyms/test_intel_tensorflow.py
  tests/pseudonyms/test_intel_tensorflow_cpu.py
  tests/pseudonyms/test_tensorflow_gpu.py
  tests/test_pipeline_builder.py
  tests/test_pipeline_config.py
  tests/test_report.py
  tests/test_resolver.py
  tests/units/pseudonyms.py
  thoth/adviser/pipeline_builder.py
  thoth/adviser/pipeline_config.py
  thoth/adviser/pseudonym.py
  thoth/adviser/pseudonyms/__init__.py
  thoth/adviser/pseudonyms/intel_tensorflow.py
  thoth/adviser/pseudonyms/intel_tensorflow_cpu.py
  thoth/adviser/pseudonyms/tensorflow_gpu.py
  thoth/adviser/resolver.py
Labels: approved, size/XXL

#1383 Pseudonyms testsuite
  tests/test_resolver.py
  tests/units/pseudonyms.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#1387 Return pytest.skip if the pipeline unit cannot be verified
  tests/base.py
  tests/test_resolver.py
Labels: approved, size/S

#1389 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1390 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/S

#1391 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1393 Automatic update of dependency voluptuous from 0.11.7 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1400 Pass package_name from unit configuration
  tests/base.py
  tests/conftest.py
  tests/pseudonyms/test_intel_tensorflow.py
  tests/pseudonyms/test_tensorflow_gpu.py
  tests/test_pipeline_builder.py
  tests/test_pipeline_config.py
  tests/units/pseudonyms.py
  thoth/adviser/pipeline_builder.py
  thoth/adviser/pseudonym.py
  thoth/adviser/pseudonyms/intel_tensorflow.py
  thoth/adviser/pseudonyms/intel_tensorflow_cpu.py
  thoth/adviser/pseudonyms/tensorflow_gpu.py
Labels: approved, size/M

#1401 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.12
  Pipfile.lock
Labels: approved, bot, size/S

#1402 Automatic update of dependency thoth-storages from 0.25.12 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/XS

#1404 Optimize sieve and steps calls that are specific for a package
  README.rst
  docs/source/sieves.rst
  docs/source/steps.rst
  tests/base.py
  tests/conftest.py
  tests/sieves/test_abi_compat.py
  tests/sieves/test_solved.py
  tests/sieves/test_version_constraint.py
  tests/steps/test_dropout.py
  tests/test_pipeline_builder.py
  tests/test_pipeline_config.py
  tests/test_report.py
  tests/test_resolver.py
  tests/units/sieves.py
  tests/units/steps.py
  thoth/adviser/boots/_debug/memtrace.py
  thoth/adviser/exceptions.py
  thoth/adviser/pipeline_builder.py
  thoth/adviser/pipeline_config.py
  thoth/adviser/pseudonym.py
  thoth/adviser/pseudonyms/intel_tensorflow.py
  thoth/adviser/pseudonyms/tensorflow_gpu.py
  thoth/adviser/resolver.py
  thoth/adviser/sieve.py
  thoth/adviser/sieves/abi_compat.py
  thoth/adviser/sieves/backports/enum34.py
  thoth/adviser/sieves/backports/functools32.py
  thoth/adviser/sieves/backports/importlib_metadata.py
  thoth/adviser/sieves/backports/importlib_resources.py
  thoth/adviser/sieves/backports/mock.py
  thoth/adviser/sieves/index_enabled.py
  thoth/adviser/sieves/locked.py
  thoth/adviser/sieves/pandas/py36_drop.py
  thoth/adviser/sieves/prereleases.py
  thoth/adviser/sieves/setuptools/py36.py
  thoth/adviser/sieves/solved.py
  thoth/adviser/sieves/tensorflow/tf_cuda.py
  thoth/adviser/sieves/version_constraint.py
  thoth/adviser/step.py
  thoth/adviser/steps/_debug/mock_score.py
  thoth/adviser/steps/aicoe.py
  thoth/adviser/steps/cve.py
  thoth/adviser/steps/dropout.py
  thoth/adviser/steps/security_indicators.py
  thoth/adviser/steps/tensorflow/tf_113_numpy.py
  thoth/adviser/steps/tensorflow/tf_114_gast.py
  thoth/adviser/steps/tensorflow/tf_21_urllib3.py
  thoth/adviser/steps/tensorflow/tf_22_numpy.py
  thoth/adviser/steps/tensorflow/tf_22_prob.py
  thoth/adviser/steps/tensorflow/tf_rm_scipy.py
  thoth/adviser/strides/one_version.py
  thoth/adviser/unit.py
Labels: approved, size/XL

#1408 Add tests related to unit_run flag
  tests/test_resolver.py
Labels: approved, size/M

#1409 Add missing schema
  thoth/adviser/steps/cve.py
Labels: size/XS

#1411 Add tests for skipping a package from steps
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#1412 Use find_namespace_packages to discover all thoth-adviser modules
  setup.py
Labels: approved, size/M
