Repository thoth-station/adviser, pull requests merged in 2020-03, with the labels that each got.

#835 Remove typeshed
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#834 Introduce package source index sieve for filtering based on index
  Pipfile
  Pipfile.lock
  requirements.txt
  tests/sieves/test_filter_index.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/filter_index.py
Labels: approved, size/L

#837 Automatic update of dependency matplotlib from 3.1.3 to 3.2.0
  Pipfile.lock
Labels: bot, size/L

#838 Automatic update of dependency packaging from 20.1 to 20.3
  Pipfile.lock
Labels: bot, size/S

#839 Automatic update of dependency click from 7.0 to 7.1.1
  Pipfile.lock
Labels: bot, size/M

#843 Fixed error log and old api
  .gitignore
  thoth/adviser/cli.py
  thoth/adviser/digests_fetcher.py
Labels: approved, size/XS

#836 Generalize variables for Ceph for the workflows
  openshift/adviser-template.yaml
  workflows/templates/advise-template.yaml
Labels: approved, do-not-merge/needs-rebase, size/M

#845 Adjust string for image and key
  workflows/templates/advise-template.yaml
Labels: approved

#847 Automatic update of dependency pyyaml from 5.3 to 3.13
  Pipfile.lock
Labels: bot, size/M

#842 Prevent from OSError when the requirements string is too large
  thoth/adviser/cli.py
Labels: size/S

#848 Automatic update of dependency pytest-mypy from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot, size/S

#819 Distinguish different types of errors of adviser runs for SLO
  thoth/adviser/run.py
Labels: size/S

#849 Automatic update of dependency pytest from 5.3.5 to 5.4.1
  Pipfile.lock
Labels: bot, size/S

#850 Start using fext in adviser
  Pipfile
  Pipfile.lock
  tests/predictors/test_annealing.py
  tests/predictors/test_hill_climbing.py
  tests/predictors/test_latest.py
  tests/predictors/test_random_walk.py
  tests/predictors/test_sampling.py
  tests/test_beam.py
  tests/test_resolver.py
  thoth/adviser/beam.py
  thoth/adviser/predictor.py
  thoth/adviser/predictors/annealing.py
  thoth/adviser/predictors/hill_climbing.py
  thoth/adviser/resolver.py
  thoth/adviser/state.py
Labels: size/XL

#779 Add Python version boot
  tests/boots/test_python_version.py
  tests/test_resolver.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/python_version.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#853 Release of version 0.8.0
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot

#857 Correct space for exception message
  thoth/adviser/exceptions.py
Labels: approved

#856 Fix handling of environment markers if multiple dependencies introduce them
  tests/test_product.py
  thoth/adviser/product.py
Labels: approved, size/L

#858 Automatic update of dependency matplotlib from 3.2.0 to 3.2.1
  Pipfile.lock
Labels: bot, size/L

#859 Automatic update of dependency hypothesis from 5.6.0 to 5.6.1
  Pipfile.lock
Labels: bot, size/XS

#860 Automatic update of dependency hypothesis from 5.6.1 to 5.7.0
  Pipfile.lock
Labels: bot, size/S

#861 Wrong variable name and missing variables
  openshift/adviser-template.yaml
  workflows/templates/advise-template.yaml
Labels: approved, size/S

#862 Rewrite beam so that it does not use fext
  Pipfile
  Pipfile.lock
  tests/test_beam.py
  thoth/adviser/beam.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#863 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.4
  Pipfile.lock
Labels: bot, size/M

#864 Automatic update of dependency thoth-storages from 0.22.4 to 0.22.5
  Pipfile.lock
Labels: bot, size/XS

#865 Make sure the error report for adviser exceptions is always present
  thoth/adviser/run.py
Labels: approved

#866 Introduce user stack scoring as a base for comparision
  tests/test_resolver.py
  thoth/adviser/cli.py
  thoth/adviser/exceptions.py
  thoth/adviser/predictor.py
  thoth/adviser/resolver.py
  thoth/adviser/run.py
Labels: approved, size/XL

#867 RL based predictors implemementation
  tests/predictors/test_annealing.py
  tests/predictors/test_mcts.py
  tests/predictors/test_td.py
  thoth/adviser/predictors/__init__.py
  thoth/adviser/predictors/annealing.py
  thoth/adviser/predictors/mcts.py
  thoth/adviser/predictors/td.py
Labels: approved

#874 Automatic update of dependency hypothesis from 5.7.0 to 5.7.1
  Pipfile.lock
Labels: bot, size/M

#873 Missing parenthesis prevent sync on Ceph!!
  workflows/templates/advise-template.yaml
Labels: approved, size/XS

#877 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot

#878 Automatic update of dependency hypothesis from 5.7.1 to 5.7.2
  Pipfile.lock
Labels: bot, size/S

#879 Automatic update of dependency hypothesis from 5.7.2 to 5.8.0
  Pipfile.lock
Labels: bot, size/S

#881 Automatic update of dependency pyyaml from 5.3.1 to 3.13
  Pipfile.lock
Labels: bot, size/M

#875 Log resolver progress each 10%
  thoth/adviser/resolver.py
Labels: approved, size/M

#882 Document provenance checks
  docs/source/integration.rst
Labels: size/S

#886 Minor fixes in api_compat
  setup.py
  tests/sieves/test_abi_compat.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/abi_compat.py
Labels: approved, size/S

#889 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/M

#887 No need to initialize logging multiple times
  thoth/adviser/run.py
Labels: approved, size/XS

#884 Optimize termial of n computation
  thoth/adviser/state.py
Labels: approved, size/XS

#885 Fix scoring of the user stack
  thoth/adviser/resolver.py
Labels: approved, size/S

#883 Address issues spotted in resolution when MCTS is used
  tests/conftest.py
  tests/predictors/test_annealing.py
  tests/predictors/test_hill_climbing.py
  tests/predictors/test_latest.py
  tests/predictors/test_mcts.py
  tests/predictors/test_random_walk.py
  tests/predictors/test_sampling.py
  tests/predictors/test_td.py
  tests/test_beam.py
  tests/test_resolver.py
  thoth/adviser/beam.py
  thoth/adviser/cli.py
  thoth/adviser/predictor.py
  thoth/adviser/predictors/mcts.py
  thoth/adviser/resolver.py
  thoth/adviser/state.py
Labels: approved, size/L

#888 Add option consider/do not consider dev dependencies
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  thoth/adviser/cli.py
  thoth/adviser/run.py
  workflows/templates/advise-template.yaml
Labels: approved, size/M

#890 Do not keep beam history if not necessary
  thoth/adviser/resolver.py
Labels: approved

#891 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/M

#892 Automatic update of dependency thoth-solver from 1.5.0 to 1.5.1
  Pipfile.lock
Labels: bot, size/XS

#894 Introduce heat up part of MCTS
  tests/predictors/test_mcts.py
  thoth/adviser/predictors/mcts.py
Labels: approved

#895 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot, size/M
