Repository thoth-station/adviser, pull requests merged in 2020-01, with the labels that each got.

#666 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/S

#667 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#669 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: bot, size/XS

#657 Exclude reports from run error in Sentry
  openshift/job-adviser-template.yaml
Labels: approved, size/XS

#670 Fixed adviser Workflow template
  openshift/workflow-adviser-template.yaml
Labels: approved, size/M

#659 Add a boot for mapping UBI to RHEL
  tests/boots/test_ubi.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/ubi.py
Labels: approved, needs-rebase, size/L

#671 Remove environment serialization - it takes some time during runs
  thoth/adviser/sieves/solved.py
Labels: size/XS

#673 Introduce beam.get_random()
  tests/test_beam.py
  thoth/adviser/beam.py
  thoth/adviser/predictors/random_walk.py
Labels: size/M

#676 Fixed missing emptyDir in the Adviser Workflow
  openshift/workflow-adviser-template.yaml
Labels: approved, size/XS

#678 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: approved, bot, size/M

#677 Beam is part of context, no need to pass it explictly
  tests/conftest.py
  tests/predictors/test_annealing.py
  tests/predictors/test_hill_climbing.py
  tests/predictors/test_random_walk.py
  tests/predictors/test_sampling.py
  tests/test_beam.py
  tests/test_resolver.py
  thoth/adviser/beam.py
  thoth/adviser/predictor.py
  thoth/adviser/predictors/annealing.py
  thoth/adviser/predictors/hill_climbing.py
  thoth/adviser/predictors/random_walk.py
  thoth/adviser/predictors/sampling.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#675 Limit number of software stacks to 1 on LATEST
  app.sh
Labels: approved, size/XS

#672 Reward signal now accepts resolver context
  tests/test_resolver.py
  thoth/adviser/predictor.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#674 Introduce beam.reset()
  tests/test_beam.py
  thoth/adviser/beam.py
Labels: approved, size/M

#679 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#681 Automatic update of dependency pyyaml from 5.2 to 5.3
  Pipfile.lock
Labels: bot, size/M

#682 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/M

#684 Automatic update of dependency thoth-python from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/XS

#685 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.5
  Pipfile.lock
Labels: bot, size/XS

#683 Introduce solved software environment boot
  tests/boots/test_solved_software_environment.py
  tests/conftest.py
  tests/test_context.py
  tests/test_resolver.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/solved_software_environment.py
Labels: approved, size/L

#686 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: size/XS

#688 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#687 Boots can raise not acceptable
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#689 Automatic update of dependency thoth-storages from 0.20.5 to 0.20.6
  Pipfile.lock
Labels: bot, size/S

#690 Automatic update of dependency thoth-python from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: bot, size/S

#691 Adjust env variable name
  openshift/workflow-adviser-template.yaml
Labels: approved, size/XS

#692 Automatic update of dependency thoth-solver from 1.4.1 to 1.5.0
  Pipfile.lock
Labels: bot, size/XS

#693 Extend resolver testsuite
  tests/test_resolver.py
Labels: approved, size/L

#694 Introduce termial function to prefer more recent versions randomly
  tests/test_state.py
  thoth/adviser/predictors/random_walk.py
  thoth/adviser/predictors/sampling.py
  thoth/adviser/state.py
Labels: approved, size/L

#695 Automatic update of dependency thoth-python from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot, size/S

#696 Sort direct dependencies for reproducible resolver runs
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#698 State pip/pip-compile support in integration section
  docs/source/integration.rst
Labels: approved, size/S

#697 Correct wrong key in template
  openshift/workflow-adviser-template.yaml
Labels: approved, size/XS

#699 Add a note on requirements.txt
  docs/source/integration.rst
Labels: approved, size/XS

#701 Yield from generator to keep context
  thoth/adviser/resolver.py
Labels: approved, size/XS

#704 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#706 Fix decision type environment variable name
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/S

#705 There is no option dependency monkey limit
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/XS

#707 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/S

#708 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/XS

#709 Add ability to block pipeline units during pipeline build
  README.rst
  tests/test_pipeline_builder.py
  thoth/adviser/pipeline_builder.py
Labels: approved, size/M

#710 Add a boot that checks for fully specified environment
  tests/boots/test_fully_specified_environment.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/fully_specified_environment.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/steps/__init__.py
  thoth/adviser/strides/__init__.py
  thoth/adviser/wraps/__init__.py
Labels: approved, size/L

#712 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/S

#715 Set random walk as default predictor for Dependency Monkey
  thoth/adviser/cli.py
Labels: approved, size/XS

#714 Inspection endpoint does not accept runtime environment
  thoth/adviser/dependency_monkey.py
Labels: approved, size/XS

#713 Fix submitting inspections
  thoth/adviser/cli.py
  thoth/adviser/dependency_monkey.py
Labels: approved, size/XS

#717 Release of version 0.7.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/L

#718 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/L

#719 Release of version 0.7.2
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, do-not-merge/needs-rebase, size/L

#721 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/XS

#722 Introduce assigned context to predictor
  tests/conftest.py
  tests/predictors/test_annealing.py
  tests/predictors/test_hill_climbing.py
  tests/predictors/test_random_walk.py
  tests/predictors/test_sampling.py
  tests/test_predictor.py
  tests/test_resolver.py
  thoth/adviser/predictor.py
  thoth/adviser/predictors/annealing.py
  thoth/adviser/predictors/hill_climbing.py
  thoth/adviser/predictors/random_walk.py
  thoth/adviser/predictors/sampling.py
  thoth/adviser/resolver.py
  thoth/adviser/unit.py
Labels: approved, size/L

#723 Predictor should pick key to beam
  tests/predictors/test_annealing.py
  tests/predictors/test_hill_climbing.py
  tests/predictors/test_random_walk.py
  tests/predictors/test_sampling.py
  tests/test_beam.py
  tests/test_resolver.py
  thoth/adviser/beam.py
  thoth/adviser/predictor.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#720 Extend docs with MDP
  docs/source/_static/mdp.dia
  docs/source/_static/mdp.png
  docs/source/introduction.rst
  docs/source/predictor.rst
  docs/source/resolver.rst
Labels: approved, size/L

#724 Introduce finalizers for predictor's memory footprint optimization
  tests/test_resolver.py
  thoth/adviser/predictor.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#725 Remove accidentally committed print statement
  thoth/adviser/predictor.py
Labels: approved, size/XS

#727 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/M

#732 Introduce a method for getting a state by its id
  tests/test_beam.py
  thoth/adviser/beam.py
Labels: approved, size/S

#731 Fix exception error messages produced
  thoth/adviser/resolver.py
Labels: approved, size/XS

#733 Reward signal now propagates state for which the reward signal is computed
  tests/test_resolver.py
  thoth/adviser/predictor.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#730 Fix beam method signatures
  thoth/adviser/beam.py
Labels: approved, size/XS

#729 Remove unused import statement
  tests/predictors/test_hill_climbing.py
Labels: approved, size/XS

#728 Introduce approximating latest predictor
  tests/predictors/test_latest.py
  tests/test_state.py
  thoth/adviser/cli.py
  thoth/adviser/predictors/__init__.py
  thoth/adviser/predictors/hill_climbing.py
  thoth/adviser/predictors/latest.py
  thoth/adviser/state.py
Labels: approved, size/L

#734 Log interesting checkpoints during resolution to user
  thoth/adviser/resolver.py
Labels: approved, size/M

#735 Fix log message reported
  thoth/adviser/resolver.py
Labels: approved, size/S

#726 Re-add state with no unresolved dependencies back to beam on resolution
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#737 Report error on resolution failure
  thoth/adviser/run.py
Labels: approved, size/XS

#738 Raise an error if no direct dependencies were found
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#739 Release of version 0.7.3
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/S

#740 Log pipeline speed
  thoth/adviser/resolver.py
Labels: approved, size/XS

#741 Refactor keep history into an utility function for reusability
  thoth/adviser/beam.py
  thoth/adviser/predictor.py
  thoth/adviser/utils.py
Labels: approved, size/M

#744 Log stack counter in a more human readable form
  thoth/adviser/resolver.py
Labels: approved, size/XS

#742 Propagate also expanded package tuple to reward signal
  tests/test_resolver.py
  thoth/adviser/predictor.py
  thoth/adviser/resolver.py
Labels: size/L

#745 Prevent annealing from being stuck
  thoth/adviser/predictors/annealing.py
Labels: approved, size/XS

#743 Fix bug shown when sieves or steps filtered out dependecies
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#746 Optimize handling of the top state kept in beam
  thoth/adviser/beam.py
Labels: approved, size/M

#747 Terminal output is slow, log only after N stacks generated
  thoth/adviser/resolver.py
Labels: approved, size/M

#749 Move log_once to utils function
  thoth/adviser/product.py
  thoth/adviser/resolver.py
  thoth/adviser/utils.py
Labels: approved, size/M

#748 Optimize state removal out of beam
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#750 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/M

#755 Fix handling of --dry-run parameter
  thoth/adviser/dependency_monkey.py
Labels: approved, size/S

#753 Include random decision stride only explictly
  thoth/adviser/strides/random_decision.py
Labels: approved, size/XS

#756 Add missing metadata to adviser job template
  openshift/job-adviser-template.yaml
Labels: approved, size/XS

#757 Fix default value key
  openshift/job-adviser-template.yaml
Labels: approved, size/XS

#759 Assign correct default value
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/XS

#758 Do not keep history in adviser runs
  openshift/job-adviser-template.yaml
Labels: approved, size/XS

#754 Show version of direct dependencies explictly
  thoth/adviser/resolver.py
Labels: approved, size/XS

#752 Introduce stride for getting one version in a stack
  tests/strides/test_one_version.py
  thoth/adviser/strides/__init__.py
  thoth/adviser/strides/one_version.py
Labels: approved, size/L

#760 Adjust limit latest versions and beam width
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
Labels: approved, size/M

#763 Use WARNING log level in thoth.common
  openshift/job-adviser-template.yaml
Labels: approved, size/XS

#762 Ask for thoth.adviser log to have clean logs and respect log configuration
  thoth/adviser/cli.py
Labels: approved, size/XS

#761 Use epsilon greedy strategy for picking the latest version
  thoth/adviser/state.py
Labels: approved, size/S

#764 Do not show information about results being submitted to result API
  openshift/job-adviser-template.yaml
Labels: approved, size/XS

#751 Introduce version constrain sieve pipeline unit
  Pipfile
  Pipfile.lock
  tests/sieves/test_version_constraint.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/version_constraint.py
Labels: approved, size/L

#766 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/L

#767 Fix a bug when env is not fully specified and env marker filters out deps
  thoth/adviser/product.py
Labels: approved, size/S

#770 Disable dry run for Thoth's recommendations
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#769 Rename template for workflow-operator
  openshift/job-adviser-template.yaml
  openshift/job-dependencyMonkey-template.yaml
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/XS

#771 Try its best to always come up with a latest stack
  thoth/adviser/predictors/latest.py
Labels: approved, size/S

#772 Automatic update of dependency thoth-storages from 0.21.7 to 0.21.8
  Pipfile.lock
Labels: bot, size/M

#773 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/XS

#774 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/S

#775 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#776 Automatic update of dependency packaging from 20.0 to 20.1
  Pipfile.lock
Labels: bot, size/L

#777 Introduce RHEL version boot for RHEL major releases
  tests/boots/test_rhel_version.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/rhel_version.py
Labels: approved, size/L

#778 Introduce normalization of score returned by step units
  .coafile
  tests/test_resolver.py
  tests/test_step.py
  thoth/adviser/resolver.py
  thoth/adviser/step.py
Labels: approved, size/L

#782 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/M

#783 Capture CLI parameters in resolver's context
  thoth/adviser/cli.py
  thoth/adviser/context.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#785 Do identity check instead of equality check
  thoth/adviser/beam.py
Labels: approved, size/XS

#789 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/M
