Repository thoth-station/adviser, pull requests merged in 2020-05, with the labels that each got.

#960 Automatic update of dependency hypothesis from 5.10.4 to 5.10.5
  Pipfile.lock
Labels: bot, size/L

#957 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: approved, bot, size/S

#962 Automatic update of dependency hypothesis from 5.10.5 to 5.11.0
  Pipfile.lock
Labels: bot, size/S

#958 Sync variable fix for provenance check
  openshift/job-provenanceChecker-template.yaml
Labels: approved, size/XS

#964 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#973 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/XS

#972 Automatic update of dependency hypothesis from 5.11.0 to 5.13.1
  Pipfile.lock
Labels: bot, size/M

#974 Automatic update of dependency hypothesis from 5.13.1 to 5.14.0
  Pipfile.lock
Labels: bot, size/XS

#975 Automatic update of dependency toml from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/XS

#980 Automatic update of dependency packaging from 20.3 to 20.4
  Pipfile.lock
Labels: bot, size/L

#981 Automatic update of dependency hypothesis from 5.14.0 to 5.15.0
  Pipfile.lock
Labels: bot, size/M

#968 Use thoth-toolbox (with Thamos) from upstream
  openshift/adviser-template.yaml
  workflows/templates/finished-webhook-template.yaml
Labels: approved, size/S

#961 Point to s2i-example-migration
  docs/source/integration.rst
Labels: approved, size/XS

#979 Fix links to docs and add s2i migration video
  docs/source/integration.rst
Labels: approved, size/S

#970 Improve message provided to user
  thoth/adviser/resolver.py
Labels: approved, size/XS

#985 Automatic update of dependency hypothesis from 5.15.0 to 5.15.1
  Pipfile.lock
Labels: bot, size/M

#986 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/XS

#983 Add unsolved-package-handler to adviser workflow
  openshift/adviser-template.yaml
Labels: approved, size/S

#987 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/S

#989 Release of version 0.9.5
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: bot, size/M

#992 Automatic update of dependency hypothesis from 5.15.1 to 5.16.0
  Pipfile.lock
Labels: bot, size/S

#993 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/M
