Repository thoth-station/adviser, pull requests merged in 2020-12, with the labels that each got.

#1600 Updated marketplace app link
  docs/source/integration.rst
Labels: approved, size/XS

#1603 Fix testsuite for Python 3.8
  tests/predictors/test_td.py
  tests/wraps/tensorflow/test_mkl_threads.py
  tests/wraps/tensorflow/test_tf_mkl_threads.py
Labels: approved, size/S

#1588 Improve error message reported to the user
  thoth/adviser/run.py
Labels: approved, size/XS

#1607 Relock so that typing extensions have the right environment marker
  Pipfile.lock
Labels: approved, size/L

#1605 Recommend TensorFlow 2.4 based on CUDA support
  tests/sieves/tensorflow/test_tf_cuda.py
  thoth/adviser/sieves/tensorflow/tf_cuda.py
Labels: approved, size/S

#1611 Add justification to stack info if a package with CVE is avoided
  tests/steps/test_cve.py
  thoth/adviser/steps/cve.py
Labels: approved, kind/feature, sig/advisor, size/S
