Repository thoth-station/adviser, pull requests merged in 2021-03, with the labels that each got.

#1713 Propagate parsed Dependency Monkey inputs to the resulting JSON output
  thoth/adviser/cli.py
Labels: approved, lgtm, size/XS

#1708 Remove bits related to preparation
  prepare.py
Labels: approved, lgtm, size/XS

#1717 Fixes related to thoth-common adjustments
  tests/test_product.py
Labels: approved, size/XS

#1721 Fix when package version is any version
  thoth/adviser/solver.py
Labels: approved, size/XS

#1719 Add justification for index configuration filter
  tests/sieves/test_experimental_conf_index.py
  thoth/adviser/sieves/experimental_filter_conf_index.py
Labels: approved, size/M

#1718 Provide justification when filtering based on selective pre-releases
  tests/sieves/test_experimental_prereleases.py
  thoth/adviser/sieves/experimental_prereleases.py
Labels: approved, size/M

#1720 Add justification for filtering packages based on index configuration
  tests/sieves/test_experimental_package_index.py
  thoth/adviser/sieves/experimental_package_index.py
Labels: approved, size/M

#1726 Remove user's stack if any changes in requirements were detected
  tests/boots/test_pipfile_hash.py
  thoth/adviser/boots/pipfile_hash.py
Labels: approved, size/M

#1733 Manual dependency update
  Pipfile.lock
Labels: approved, size/M

#1729 Remove user's stack if development dependencies are not present
  MANIFEST.in
  tests/boots/test_pipfile_hash.py
  tests/data/projects/dev/Pipfile
  tests/data/projects/dev/Pipfile.lock
  thoth/adviser/boots/pipfile_hash.py
Labels: approved, size/L

#1730 Fix missing thoth section in the recommended stack
  tests/test_product.py
  tests/test_report.py
  thoth/adviser/product.py
Labels: approved, size/S

#1727 Fix justification messages reported by backport sieves
  tests/sieves/backports/test_enum34.py
  tests/sieves/backports/test_functools32.py
  tests/sieves/backports/test_importlib_metadata.py
  tests/sieves/backports/test_importlib_resources.py
  tests/sieves/backports/test_mock.py
  thoth/adviser/sieves/backports/enum34.py
  thoth/adviser/sieves/backports/functools32.py
  thoth/adviser/sieves/backports/importlib_metadata.py
  thoth/adviser/sieves/backports/importlib_resources.py
  thoth/adviser/sieves/backports/mock.py
Labels: approved, size/M

#1734 Fix link to Thoth s2i info
  thoth/adviser/wraps/thoth_s2i_info.py
Labels: approved, size/XS

#1736 Adjust type of the message for S2I info
  thoth/adviser/wraps/thoth_s2i_info.py
Labels: approved, size/XS

#1625 Propagate metadata to justification and stack info
  tests/test_product.py
  tests/test_report.py
  thoth/adviser/product.py
  thoth/adviser/report.py
Labels: do-not-merge/work-in-progress, size/M

#1738 Normalize score returned from CVE step score
  thoth/adviser/steps/cve.py
Labels: approved, size/XS

#1748 Fix typing for prescription units and core units
  tests/test_resolver.py
  thoth/adviser/pipeline_builder.py
  thoth/adviser/prescription/v1/boot.py
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/pseudonym.py
  thoth/adviser/prescription/v1/sieve.py
  thoth/adviser/prescription/v1/step.py
  thoth/adviser/prescription/v1/unit.py
  thoth/adviser/resolver.py
  thoth/adviser/unit_types.py
Labels: approved, size/L

#1752 Provide a sub-command to validate prescription YAML
  thoth/adviser/cli.py
Labels: approved, size/XS

#1750 Add a note to prescription docs
  docs/source/prescription.rst
Labels: approved, size/S

#1754 Improve type handling in the prescription module
  thoth/adviser/pipeline_builder.py
  thoth/adviser/prescription/v1/prescription.py
Labels: size/M

#1755 Add extend justification links if links do not point to any hosted site
  docs/source/prescription.rst
  thoth/adviser/prescription/v1/step.py
  thoth/adviser/prescription/v1/unit.py
  thoth/adviser/prescription/v1/wrap.py
Labels: approved, size/M

#1757 Add URL to logged message automatically
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/XS

#1756 Register UBI boot only if UBI is used
  tests/boots/test_ubi.py
  thoth/adviser/boots/ubi.py
Labels: approved, size/M

#1758 State logged message rather than logged text
  docs/source/prescription.rst
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
  thoth/adviser/sieves/experimental_package_index.py
Labels: approved, size/S

#1761 Add release and data infor to the prescription chema
  docs/source/prescription.rst
  thoth/adviser/prescription/v1/schema.py
Labels: approved, size/XS

#1762 Prescription listing
  docs/source/prescription.rst
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: size/L

#1764 Allow multiple hardware configurations per pipeline unit
  docs/source/prescription.rst
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/M

#1767 Allow multiple prescription files being supplied to the resolver
  thoth/adviser/cli.py
  thoth/adviser/exceptions.py
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
Labels: size/L

#1769 Test loading prescriptions
  docs/source/prescription.rst
  tests/data/prescriptions/basic.yaml
  tests/prescription/v1/test_prescription.py
  tests/test_pipeline_builder.py
  thoth/adviser/prescription/v1/prescription.py
Labels: approved, size/L

#1770 Add a pipeline unit that notifies about prescription release used
  tests/boots/test_prescription_release.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/prescription_release.py
  thoth/adviser/context.py
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#1773 Relax strict match for prescription wrap pipeline units
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/XS

#1775 Add ability to yield matched package version in pseudonyms
  docs/source/prescription.rst
  tests/prescription/v1/test_pseudonym.py
  thoth/adviser/prescription/v1/pseudonym.py
  thoth/adviser/prescription/v1/schema.py
Labels: approved, size/M

#1778 Adjust pseudonym example with yield matched version
  docs/source/prescription.rst
Labels: approved, size/XS

#1777 Do not enforce operating system to be set for matching
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/XS

#1779 Introduce namespace for prescriptions
  tests/boots/test_prescription_release.py
  tests/data/prescriptions/basic.yaml
  tests/prescription/v1/test_prescription.py
  thoth/adviser/boots/prescription_release.py
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
Labels: approved, size/M

#1780 Remove wisdom from the prescription yaml
  docs/source/prescription.rst
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
Labels: approved, size/XS

#1781 Implement prescription validation with semantics
  docs/source/prescription.rst
  thoth/adviser/cli.py
  thoth/adviser/prescription/v1/prescription.py
Labels: approved, size/L

#1626 Add Thoth's landing page
  docs/source/index.rst
  docs/source/landing_page.rst
Labels: approved, sig/docs, size/M

#1785 Report stack info just once in prescription units
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/XS

#1786 Update prescription documentation so users can start using it
  docs/source/justifications.rst
  docs/source/prescription.rst
Labels: approved, size/XXL

#1787 Use package name from configuration to reduce some hashing
  thoth/adviser/wraps/tensorflow/tf_42475.py
Labels: size/XS

#1788 Be more positive with justification message reported
  thoth/adviser/wraps/no_onservation.py
Labels: approved, size/XS

#1789 Rewrite s2i wraps to boots to match semantics
  tests/boots/test_thoth_s2i.py
  tests/boots/test_thoth_s2i_info.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/thoth_s2i.py
  thoth/adviser/boots/thoth_s2i_info.py
  thoth/adviser/wraps/__init__.py
Labels: size/M

#1739 change si scoring and add info justification
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/S

#1791 Fix step example in prescriptions
  docs/source/prescription.rst
Labels: approved, size/S

#1790 Adjustments in security indicators
  tests/steps/test_security_indicators.py
  thoth/adviser/steps/security_indicators.py
Labels: approved, size/S

#1792 Register core units first before any prescriptions
  thoth/adviser/pipeline_builder.py
Labels: approved, size/S

#1793 Allow supplying expected library usage in prescriptions
  docs/source/prescription.rst
  tests/prescription/v1/test_unit.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/L

#1794 Add ability to declare advised manifest changes in wrap prescriptions
  docs/source/prescription.rst
  tests/prescription/v1/test_wrap.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/wrap.py
Labels: approved, size/L

#1795 Add "not" operator to the prescription declaration
  docs/source/prescription.rst
  tests/prescription/v1/test_unit.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/L

#1796 Move MKL specific wrap to prescriptions
  tests/wraps/tensorflow/test_mkl_threads.py
  tests/wraps/tensorflow/test_tf_mkl_threads.py
  thoth/adviser/wraps/tensorflow/__init__.py
  thoth/adviser/wraps/tensorflow/tf_mkl_threads.py
Labels: size/L

#1797 Fix handling prescription unit names
  thoth/adviser/pipeline_builder.py
  thoth/adviser/prescription/v1/unit.py
  thoth/adviser/unit.py
  thoth/adviser/wraps/__init__.py
Labels: approved, size/M

#1798 Fix handling optimized wrap call based on product score
  thoth/adviser/report.py
  thoth/adviser/resolver.py
Labels: approved, size/S

#1799 Remove TF Keras embedding wrap that was moved to prescriptions
  tests/wraps/tensorflow/test_tf_42475.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/tensorflow/__init__.py
  thoth/adviser/wraps/tensorflow/tf_42475.py
Labels: approved, size/L

#1800 Keep optimization for prescription wraps with resolved dependencies
  tests/prescription/v1/test_wrap.py
  thoth/adviser/prescription/v1/wrap.py
Labels: approved, size/M
