Repository thoth-station/adviser, pull requests merged in 2021-07, with the labels that each got.

#1949 Point users to support repository to report issues
  docs/source/index.rst
Labels: approved, size/XS

#1958 Update TensorFlow API symbols to include symbols in 2.6 release
  thoth/adviser/data/tensorflow/api.json
Labels: approved, size/XXL

#1959 TensorFlow 2.5 is built with CUDA 11.2 support
  thoth/adviser/sieves/tensorflow/tf_cuda.py
Labels: approved, size/XS

#1957 Implement a pipeline unit for filtering Python packages already present in the base
  tests/base.py
  tests/sieves/test_thoth_s2i_packages.py
  thoth/adviser/exceptions.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/thoth_s2i_packages.py
Labels: approved, size/L

#1947 Introduce a mechanism for including unit based on Python packages
  docs/source/prescription.rst
  tests/prescription/v1/test_unit.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/L

#1962 Use CLoader to load prescriptions to speed up loading
  tests/prescription/v1/test_prescription.py
  thoth/adviser/prescription/v1/prescription.py
Labels: approved, lgtm, size/XS

#1972 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, size/S

#1966 Add a wrap that notifies about Python package releases on PyPI
  tests/test_product.py
  tests/wraps/test_no_observation.py
  tests/wraps/test_pypi_release.py
  thoth/adviser/product.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/pypi_release.py
Labels: approved, lgtm, size/L

#1973 TensorFlow 2.6 uses same CUDA as TensorFlow 2.5, CUDA 11.2
  thoth/adviser/sieves/tensorflow/tf_cuda.py
Labels: approved, size/XS

#1974 Notify about packages published on Operate First Pulp instance
  tests/wraps/test_pulp_release.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/pulp_release.py
Labels: approved, size/L

#1977 Use orjson to load TensorFlow API symbols
  Pipfile
  Pipfile.lock
  thoth/adviser/sieves/tensorflow/tf_api.py
Labels: approved, size/L

#1981 Use prescriptions, plural
  tests/boots/test_prescription_release.py
  thoth/adviser/boots/prescription_release.py
Labels: approved, size/XS

#1980 State also package version when notifying about PyPI packages
  tests/wraps/test_pypi_release.py
  thoth/adviser/wraps/pypi_release.py
Labels: approved, size/XS

#1984 Rename build time error to installation time error
  thoth/adviser/sieves/solved.py
Labels: approved, size/XS

#1986 Decrease log level accidentally stated as error
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/XS

#1995 Fix wrong import
  thoth/adviser/cli.py
Labels: approved, size/XS

#2003 Pin flexmock to <=0.10.4
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#1993 Add package name to Pulp information
  tests/wraps/test_pulp_release.py
  thoth/adviser/wraps/pulp_release.py
Labels: size/XS

#1994 Sort resulting justification for better UX
  tests/wraps/test_sort_justifications.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/sort_justifications.py
Labels: size/L

#1991 Link package information to libraries.io
  tests/wraps/test_libraries_io.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/libraries_io.py
Labels: size/L

#1992 Add package name to PyPI release justification info
  tests/wraps/test_pypi_release.py
  thoth/adviser/wraps/pypi_release.py
Labels: size/XS

#1989 Do not add scored user stack to beam
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: do-not-merge/hold, size/S

#1979 State dependency graph in the resulting document
  tests/test_product.py
  tests/test_report.py
  thoth/adviser/product.py
Labels: size/L

#2006 Make Pulp URL configurable
  tests/wraps/test_pulp_release.py
  thoth/adviser/wraps/pulp_release.py
Labels: approved

#2012 Improve parsing of Python package name and extend justification
  thoth/adviser/prescription/v1/schema.py
Labels: approved, size/M

#2013 Rename shared objects to ABI
  docs/source/prescription.rst
  tests/prescription/v1/test_unit.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/M

#2015 Implement "globbing" when including units based on detected libs
  docs/source/prescription.rst
  tests/prescription/v1/test_unit.py
  thoth/adviser/prescription/v1/unit.py
Labels: size/M

#2011 Derive information from trove classifiers for users
  tests/wraps/test_trove_classifiers.py
  thoth/adviser/wraps/__init__.py
  thoth/adviser/wraps/trove_classifiers.py
Labels: approved, size/XL

#2023 Make wrap match part optional
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/wrap.py
Labels: approved, size/XS
