Repository thoth-station/adviser, pull requests merged in 2021-05, with the labels that each got.

#1848 Add support for skip package prescription unit
  docs/source/prescription.rst
  tests/prescription/v1/test_skip_package.py
  thoth/adviser/prescription/v1/__init__.py
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/skip_package.py
Labels: approved, size/L

#1858 Log removal of a legacy version just once
  thoth/adviser/sieves/legacy_version.py
Labels: approved, size/S

#1864 Report all unresolved dependencies
  thoth/adviser/resolver.py
Labels: approved, size/S

#1863 Make boot pipeline unit responsible for providing stack info
  tests/boots/test_fully_specified_environment.py
  thoth/adviser/boots/fully_specified_environment.py
  thoth/adviser/boots/solved_software_environment.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#1867 Handle error when all the direct deps are sieved
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, lgtm, size/M

#1870 Add video demonstrating constaints.txt use
  docs/source/experimental_features.rst
Labels: approved, size/XS

#1869 update the prow resource limits
  .prow.yaml
Labels: approved, size/S
