Repository thoth-station/adviser, pull requests merged in 2021-06, with the labels that each got.

#1868 Updates to website
  docs/source/architecture.rst
  docs/source/deployment.rst
  docs/source/developers_guide.rst
  docs/source/pipeline.rst
  docs/source/predictors/annealing.rst
  docs/source/predictors/latest.rst
Labels: approved, lgtm, size/M

#1878 Document solver rules
  docs/source/deployment.rst
Labels: approved, size/S

#1877 Add a sieve implementing filtering based on solver rules
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/rules.py
Labels: approved, size/L

#1876 Adjust for CVEs consumed from PyPA
  tests/steps/test_cve.py
  thoth/adviser/steps/cve.py
Labels: approved, size/M

#1882 Keep CVE advisory in the justification output
  tests/steps/test_cve.py
  thoth/adviser/steps/cve.py
Labels: approved, size/XS

#1889 Introduce labels to the resolution engine
  docs/source/prescription.rst
  prepare.py
  tests/conftest.py
  tests/prescription/v1/test_unit.py
  tests/test_context.py
  tests/test_pipeline_builder.py
  tests/test_resolver.py
  thoth/adviser/cli.py
  thoth/adviser/context.py
  thoth/adviser/pipeline_builder.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
  thoth/adviser/resolver.py
Labels: approved, size/L

#1890 Add tests for solver rules
  tests/test_rules.py
Labels: approved, size/L

#1895 Notify users about labels used during the resolution process
  tests/boots/test_labels.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/labels.py
Labels: approved, size/L

#1898 Fix wrong read variable
  thoth/adviser/cli.py
Labels: approved, size/XS

#1896 Notify users if they use runtime environment not known to deployment
  Pipfile
  Pipfile.lock
  tests/boots/test_solvers_configured.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/solvers_configured.py
Labels: approved, size/L

#1903 Add update sieve responsible for package updates
  tests/sieves/test_update.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/update.py
Labels: approved, size/L

#1905 Fix wrong CVE key obtained
  tests/steps/test_cve.py
  thoth/adviser/steps/cve.py
Labels: approved, size/XS

#1910 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, bot, size/XS

#1913 Turn warning to debug message
  thoth/adviser/resolver.py
Labels: approved, size/XS

#1916 Add YouTube video for solver rules
  docs/source/deployment.rst
Labels: approved, size/XS

#1920 updates from the template project
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, size/S

#1917 Load prescriptions from a directory structure
  tests/boots/test_prescription_release.py
  tests/data/prescriptions/_prescription_metadata.yaml
  tests/data/prescriptions/basic.yaml
  tests/data/prescriptions/units/basic.yaml
  tests/prescription/v1/test_prescription.py
  thoth/adviser/prescription/__init__.py
  thoth/adviser/prescription/v1/__init__.py
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
Labels: approved, lgtm, size/L

#1929 Adjust validate logic to consume prescriptions from a dir
  thoth/adviser/cli.py
  thoth/adviser/prescription/v1/prescription.py
Labels: approved, size/M

#1927 Filter Python packages present in software stack based on so files
  docs/source/prescription.rst
  tests/prescription/v1/test_unit.py
  thoth/adviser/exceptions.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/sieve.py
  thoth/adviser/prescription/v1/unit.py
  thoth/adviser/sieves/thoth_s2i_abi_compat.py
  thoth/adviser/unit.py
Labels: approved, size/L

#1928 Perform recommendations based on RPM packages present in the environment
  docs/source/prescription.rst
  tests/prescription/v1/test_unit.py
  thoth/adviser/prescription/v1/schema.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/L

#1921 add docs for security advises
  docs/source/security.rst
Labels: approved, lgtm, size/M

#1933 Adjust reporting of RPM and SO specific issues
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/M

#1936 Add graph-metrics-exporter
  docs/source/architecture.rst
Labels: approved, size/XS

#1934 Extend documentation for security
  docs/source/index.rst
  docs/source/security.rst
Labels: approved, size/M

#1940 Fix docs for shared objects in prescriptions
  docs/source/prescription.rst
Labels: approved, size/XS

#1942 Add demos from sprint 63
  docs/source/prescription.rst
Labels: approved, size/S

#1941 docs: Add pulp-python monitoring job
  docs/source/architecture.rst
Labels: approved, do-not-merge/hold, size/XS

#1944 Keep pipeline run information only when adviser is run in verbose mode
  tests/test_report.py
  thoth/adviser/cli.py
  thoth/adviser/dm_report.py
  thoth/adviser/report.py
  thoth/adviser/run.py
Labels: approved, lgtm, size/M
