Repository thoth-station/adviser, pull requests merged in 2021-11, with the labels that each got.

#2148 Introduce a CVE sieve
  tests/sieves/test_cve.py
  tests/steps/test_cve.py
  thoth/adviser/sieves/__init__.py
  thoth/adviser/sieves/cve.py
  thoth/adviser/steps/cve.py
Labels: approved, size/L

#2152 Fix ABI sieve filtering packages when no image analysis is available
  tests/sieves/test_thoth_s2i_abi_compat.py
  thoth/adviser/sieves/thoth_s2i_abi_compat.py
Labels: approved, size/M

#2153 Fix matching operating system in prescriptions
  tests/prescription/v1/test_unit.py
  thoth/adviser/prescription/v1/unit.py
Labels: approved, size/XS

#2151 Provide a link to CVE based on info as present in PyPA/advisory-db
  thoth/adviser/sieves/cve.py
  thoth/adviser/steps/cve.py
Labels: approved, size/XS

#2150 Provide information about last CVE update to users
  tests/boots/test_cve_timestamp.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/cve_timestamp.py
Labels: approved, size/L

#2161 Adjust flexmock import to respect new flexmock release notes
  tests/boots/test_python_version.py
  tests/boots/test_rhel_version.py
  tests/conftest.py
  tests/predictors/test_annealing.py
  tests/predictors/test_hill_climbing.py
  tests/predictors/test_latest.py
  tests/predictors/test_mcts.py
  tests/predictors/test_random_walk.py
  tests/predictors/test_sampling.py
  tests/predictors/test_td.py
  tests/prescription/v1/test_boot.py
  tests/prescription/v1/test_gh_release_notes.py
  tests/prescription/v1/test_pseudonym.py
  tests/prescription/v1/test_sieve.py
  tests/prescription/v1/test_step.py
  tests/prescription/v1/test_stride.py
  tests/prescription/v1/test_unit.py
  tests/prescription/v1/test_wrap.py
  tests/sieves/test_index_enabled.py
  tests/sieves/test_locked.py
  tests/sieves/test_prereleases.py
  tests/sieves/test_solved.py
  tests/sieves/test_thoth_s2i_abi_compat.py
  tests/steps/test_cve.py
  tests/steps/test_security_indicators.py
  tests/test_dependency_monkey.py
  tests/test_dm_report.py
  tests/test_pipeline_builder.py
  tests/test_pipeline_config.py
  tests/test_predictor.py
  tests/test_product.py
  tests/test_resolver.py
Labels: approved, size/M

#2164 Remove unused termial function
  thoth/adviser/state.py
Labels: approved, size/S

#2156 Implement group step prescription
  docs/source/prescription/steps.rst
  tests/prescription/v1/test_group.py
  thoth/adviser/prescription/v1/__init__.py
  thoth/adviser/prescription/v1/group.py
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
Labels: approved, size/XL

#2162 Move recommendation type information more to the top
  tests/boots/test_environment_info.py
  thoth/adviser/boots/environment_info.py
Labels: approved, size/M

#2163 Document Quay security on container images
  docs/source/security.rst
Labels: approved, size/S

#2169 Fix history cleaning
  thoth/adviser/predictors/random_walk.py
Labels: approved, size/XS

#2171 Remove platform boot
  tests/boots/test_platform.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/platform.py
Labels: approved, size/L

#2167 Introduce metadata in prescriptions
  docs/source/prescription.rst
  thoth/adviser/prescription/v1/prescription.py
  thoth/adviser/prescription/v1/schema.py
Labels: approved, size/S

#2174 add kebechet to crossroads in docs
  docs/source/index.rst
Labels: approved, size/XS

#2176 Do not score user's stack if Pipfile was adjusted
  tests/test_resolver.py
  thoth/adviser/resolver.py
Labels: approved, size/S, lgtm

#2183 Fix configuration schema for group step
  tests/prescription/v1/test_group.py
  thoth/adviser/prescription/v1/group.py
Labels: approved, size/S

#2181 Allow constraints without version identifier
  tests/data/constraints/constraints_1.txt
  tests/sieves/test_constraints.py
  thoth/adviser/sieves/constraints.py
Labels: approved, size/S

#2186 Set default platform if None is explicitly provided
  thoth/adviser/cli.py
Labels: approved, size/XS

#2187 Add a boot that checks if users use supported platform
  tests/boots/test_platform.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/platform.py
Labels: approved, size/L

#2184 Fix reporting fully specified environment
  thoth/adviser/boots/fully_specified_environment.py
Labels: approved, size/S

#2194 Fix link to temporal difference learning on Wikipedia
  docs/source/predictors/temporal_difference_learning.rst
Labels: approved, size/XS

#2185 Take environment markers that match the given runtime environment
  tests/test_product.py
  thoth/adviser/product.py
Labels: approved, size/S
