Repository thoth-station/adviser, pull requests merged in 2022-01, with the labels that each got.

#2233 Update the link to Kebechet managers documentation
  docs/source/integration.rst
Labels: approved, size/XS

#2236 Remove boot that notifies about no GPU supplied
  tests/boots/test_gpu.py
  thoth/adviser/boots/__init__.py
  thoth/adviser/boots/gpu.py
Labels: approved, size/L

#2240 Use HTTPS instead of Git in pre-commit
  .pre-commit-config.yaml
Labels: approved, size/XS

#2238 Adjust the default link to Thoth search
  thoth/adviser/boots/thoth_search.py
Labels: approved, size/XS

#2241 Add missing labels to the report
  tests/test_product.py
Labels: approved, size/XS

#2248 Link tutorial from docs
  docs/source/integration.rst
Labels: approved, size/XS

#2250 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS

#2252 Respect also runtime environment when linking packages in Search
  tests/wraps/test_thoth_search_package.py
  thoth/adviser/wraps/thoth_search_package.py
Labels: approved, size/S

#2255 Remove unused .thothTemplate.yaml
  .thothTemplate.yaml
Labels: approved, size/S

#2253 Get environments from solvers configmap and fix tests for solved software environments
  tests/boots/test_solved_software_environment.py
  thoth/adviser/boots/solved_software_environment.py
Labels: approved, size/M

#2256 Skip empty lines in solvers configmap
  tests/boots/test_solved_software_environment.py
  thoth/adviser/boots/solved_software_environment.py
Labels: approved, size/S

#2257 Adjust tests when checking for solvers configured
  tests/boots/test_solved_software_environment.py
Labels: approved, size/M

#2258 Update entries in the architecture docs
  docs/source/architecture.rst
Labels: approved, size/XS
