Repository thoth-station/adviser, pull requests merged in 2022-07, with the labels that each got.

#2355 Remove the maintainers section from .thoth.yaml
  .pre-commit-config.yaml
  .thoth.yaml
  OWNERS
  thoth/adviser/unit.py
Labels: size/S

#2362 Fix docstring
  thoth/adviser/pipeline_config.py
  thoth/adviser/sieve.py
Labels: approved, size/XS

#2363 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, priority/critical-urgent, kind/bug, ok-to-test
