Repository thoth-station/adviser, pull requests merged in 2022-03, with the labels that each got.

#2284 Document memory optimizer
  docs/source/deployment.rst
Labels: approved, size/S

#2289 Add a note about memory optimizer limit
  docs/source/deployment.rst
Labels: approved, size/XS

#2300 Normalize operating system version when checking solvers configured
  thoth/adviser/boots/solvers_configured.py
Labels: approved, size/XS

#2299 SolvedSoftwareEnvironmentBoot is mentioned twice in boot listing
  thoth/adviser/boots/__init__.py
Labels: approved, size/XS

#2296 Change link to Thoth Search for a package
  thoth/adviser/wraps/thoth_search_package.py
Labels: approved, size/XS

#2313 Fix `context` to `beam` in predictor docs
  docs/source/predictor.rst
Labels: approved, size/XS

#2315 Remove documentation on `submit-amun` thoth-adviser CLI subcommand
  docs/source/dependency_monkey.rst
Labels: approved, size/XS

#2312 Update the GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/L
