Repository thoth-station/adviser, pull requests merged in 2022-06, with the labels that each got.

#2348 Implement allowing certain CVEs being present in the application stack
  tests/boots/test_labels.py
  tests/sieves/test_cve.py
  tests/test_unit.py
  thoth/adviser/boots/labels.py
  thoth/adviser/sieves/cve.py
  thoth/adviser/steps/cve.py
  thoth/adviser/unit.py
Labels: approved, size/L

#2341 Fix the URL path when pointing to the search Web UI
  .pre-commit-config.yaml
  .prow.yaml
  tests/prescription/v1/test_add_package_step.py
  tests/prescription/v1/test_gh_release_notes.py
  tests/prescription/v1/test_group.py
  tests/sieves/test_experimental_conf_index.py
  thoth/adviser/boots/environment_info.py
  thoth/adviser/boots/thoth_search.py
  thoth/adviser/predictor.py
  thoth/adviser/predictors/annealing.py
  thoth/adviser/predictors/mcts.py
  thoth/adviser/prescription/v1/unit.py
  thoth/adviser/resolver.py
Labels: approved, size/M

#2347 Update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm
