Repository thoth-station/adviser, pull requests merged in 2022-08, with the labels that each got.

#2357 Doc rewording
  docs/source/architecture.rst
Labels: approved, size/XS, ok-to-test

#2358 Fix a typo
  docs/source/pipeline.rst
Labels: approved, size/XS, ok-to-test

#2365 docs: Precision regarding graph-sync-job
  docs/source/architecture.rst
Labels: approved, size/S

#2367 Moves flake8 config into a dedicated file
  .flake8
  .pre-commit-config.yaml
  pyproject.toml
Labels: size/S, lgtm

#2369 Docs typo
  docs/source/developers_guide.rst
Labels: approved, size/XS

#2374 Release of version 0.56.1
  CHANGELOG.md
  thoth/adviser/__init__.py
Labels: approved, size/S, ok-to-test

#2373 :snail: fix the dependency issue by pinning down hypothesis
  Pipfile
  Pipfile.lock
Labels: approved, size/XL
